"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { csrfRequest } from "../../../features/dashboard-api";
import { formatMoneyAr, planTypeLabel } from "../../../lib/formatters";

type Plan = { id: string; arabicName: string; planType: string; price: number; currency: string; durationDays?: number; sessionCount?: number };
type Beneficiary = { playerDisplayName: string; sport: string; academyName: string; plans: Plan[] };
export default function Page() {
  const router = useRouter(); const [reference, setReference] = useState(""); const [beneficiary, setBeneficiary] = useState<Beneficiary | null>(null); const [selected, setSelected] = useState(""); const [error, setError] = useState(""); const plan = beneficiary?.plans.find(item => item.id === selected);
  async function resolve(event: FormEvent) { event.preventDefault(); setError(""); try { const response = await csrfRequest("/api/v1/guardian/subscriptions/external/resolve", "POST", { reference }); setBeneficiary(await response.json() as Beneficiary); } catch (caught) { setBeneficiary(null); setError(caught instanceof Error ? caught.message : "كود التجديد غير صالح أو منتهي."); } }
  async function pay() { if (!selected) return; setError(""); try { const response = await csrfRequest("/api/v1/guardian/subscriptions/external/renewals", "POST", { reference, subscriptionPlanId: selected }, { "Idempotency-Key": crypto.randomUUID() }); const result = await response.json() as { paymentId: string }; router.push(`/guardian/checkout/${result.paymentId}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر بدء الدفع."); } }
  return <main className="center-shell"><section className="authenticated-card"><span className="eyebrow">تجديد اشتراك لشخص آخر</span><h1>أدخل كود التجديد</h1><p className="intro">لا يتيح هذا الكود الوصول إلى ملف اللاعب أو بياناته الخاصة.</p><form onSubmit={event => void resolve(event)}><label className="field">كود التجديد<input dir="ltr" value={reference} onChange={event => setReference(event.target.value)} required autoComplete="off" /></label><button className="secondary-button">تحقق من الكود</button></form>{beneficiary && <section className="beneficiary-confirmation"><h2>تأكيد المستفيد</h2><dl className="identity-summary"><div><dt>اللاعب</dt><dd>{beneficiary.playerDisplayName}</dd></div><div><dt>الرياضة</dt><dd>{beneficiary.sport}</dd></div><div><dt>الأكاديمية</dt><dd>{beneficiary.academyName}</dd></div></dl><h2>اختر الباقة</h2><div className="choice-list">{beneficiary.plans.map(item => <label key={item.id}><input type="radio" name="plan" value={item.id} checked={selected === item.id} onChange={() => setSelected(item.id)} /><strong>{item.arabicName}</strong><span>{formatMoneyAr(item.price, item.currency)} · {planTypeLabel(item.planType)}</span></label>)}</div>{plan && <p className="review-box">مراجعة الدفع: {beneficiary.playerDisplayName} — {beneficiary.sport} — {plan.arabicName} — {formatMoneyAr(plan.price, plan.currency)}</p>}<button className="primary-button" disabled={!selected} onClick={() => void pay()}>الدفع الإلكتروني — ادفع الآن</button></section>}{error && <p className="error-message" role="alert">{error}</p>}</section></main>;
}
