"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { csrfRequest } from "../../../../features/dashboard-api";
import { formatMoneyAr, statusLabel } from "../../../../lib/formatters";

type Payment = { id: string; providerReference: string; amount: number; currency: string; status: string; player: string; sport: string; plan: string; originalAmount: number; discountType?: "Percentage" | "FixedAmount"; discountValue?: number; discountAmount: number; finalAmount: number; currentPaymentId: string; isCurrent: boolean; receiptId?: string };

export default function Page() {
  const paymentId = String(useParams().paymentId); const router = useRouter(); const [payment, setPayment] = useState<Payment | null>(null); const [error, setError] = useState("");
  const load = useCallback(() => fetch(`/api/v1/guardian/subscriptions/payments/${paymentId}`).then(async response => { if (!response.ok) throw new Error(); setPayment(await response.json() as Payment); }).catch(() => setError("تعذر تحميل طلب الدفع.")), [paymentId]);
  useEffect(() => { void load(); }, [load]);
  async function simulate(outcome: string) { setError(""); try { await csrfRequest(`/api/v1/guardian/subscriptions/payments/${paymentId}/simulate`, "POST", { outcome }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر تنفيذ المحاكاة."); } }
  async function retry() { setError(""); try { const response = await csrfRequest(`/api/v1/guardian/subscriptions/payments/${paymentId}/retry`, "POST", {}, { "Idempotency-Key": crypto.randomUUID() }); const result = await response.json() as { paymentId: string }; router.push(`/guardian/checkout/${result.paymentId}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر إعادة محاولة الدفع."); } }
  return <main className="center-shell"><section className="authenticated-card test-gateway"><p className="demo-note">بيئة دفع تجريبية — لا توجد أموال حقيقية</p><h1>الدفع التجريبي</h1>{error && <p className="error-message" role="alert">{error}</p>}{!payment ? <p>جارٍ التحميل…</p> : <><dl className="identity-summary"><div><dt>اللاعب والرياضة</dt><dd>{payment.player} — {payment.sport}</dd></div><div><dt>الباقة</dt><dd>{payment.plan}</dd></div>{payment.discountAmount > 0 ? <><div><dt>السعر الأصلي</dt><dd>{formatMoneyAr(payment.originalAmount, payment.currency)}</dd></div><div><dt>الخصم</dt><dd>{payment.discountType === "Percentage" ? `${payment.discountValue}%` : formatMoneyAr(payment.discountValue, payment.currency)} (-{formatMoneyAr(payment.discountAmount, payment.currency)})</dd></div><div><dt>الإجمالي بعد الخصم</dt><dd>{formatMoneyAr(payment.finalAmount, payment.currency)}</dd></div></> : <div><dt>السعر والإجمالي</dt><dd>{formatMoneyAr(payment.amount, payment.currency)}</dd></div>}<div><dt>المرجع</dt><dd dir="ltr">{payment.providerReference}</dd></div><div><dt>الحالة من الخادم</dt><dd>{statusLabel(payment.status)}</dd></div></dl>{payment.isCurrent === false && <p className="error-message">تم استبدال طلب الدفع بعد تحديث السعر. استخدم طلب الدفع الحالي.</p>}{payment.isCurrent === false && payment.currentPaymentId && <Link className="primary-action" href={`/guardian/checkout/${payment.currentPaymentId}`}>فتح طلب الدفع الحالي</Link>}{payment.isCurrent !== false && payment.status === "Pending" && <div className="gateway-actions"><button className="primary-button" onClick={() => void simulate("Success")}>محاكاة نجاح الدفع</button><button onClick={() => void simulate("Failed")}>محاكاة فشل الدفع</button><button onClick={() => void simulate("Cancelled")}>إلغاء العملية</button></div>}{payment.status === "Confirmed" && <p className="success-message">تم الدفع وتجديد الاشتراك بنجاح</p>}{payment.status === "Failed" && <p className="error-message">فشلت عملية الدفع ولم يتم تجديد الاشتراك.</p>}{payment.status === "Cancelled" && <p className="error-message">أُلغيت العملية ولم يتم تجديد الاشتراك.</p>}{payment.isCurrent !== false && ["Failed", "Cancelled", "Expired"].includes(payment.status) && <button className="primary-button" onClick={() => void retry()}>إعادة محاولة الدفع</button>}{payment.receiptId && <Link className="primary-action" href={`/guardian/receipts/${payment.receiptId}`}>عرض الإيصال</Link>}<Link className="back-link" href="/guardian">العودة للاشتراكات</Link></>}</section></main>;
}
