"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "../../../../components/dashboard-shell";
type Item = { id: string; arabicName: string; branchId?: string; sportId?: string; ageCategoryId?: string };
type Options = { branches: Item[]; sports: Item[]; categories: Item[]; groups: Item[] };
export default function NewPlayerPage() { const router = useRouter(); const [options, setOptions] = useState<Options>({ branches: [], sports: [], categories: [], groups: [] }); const [branchId, setBranch] = useState(""); const [sportId, setSport] = useState(""); const [categoryId, setCategory] = useState(""); const [error, setError] = useState(""); useEffect(() => { fetch("/api/v1/manage/structure/options").then(r => r.json()).then(setOptions); }, []); const groups = options.groups.filter(g => (!branchId || g.branchId === branchId) && (!sportId || g.sportId === sportId) && (!categoryId || g.ageCategoryId === categoryId)); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const csrf = await fetch("/api/v1/auth/csrf").then(r => r.json()) as { token: string }; const response = await fetch("/api/v1/people/registrations", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-TOKEN": csrf.token }, body: JSON.stringify({ playerArabicName: d.get("playerName"), dateOfBirth: d.get("birth"), gender: Number(d.get("gender")), guardianName: d.get("guardianName"), guardianPhone: d.get("phone"), branchId, sportId, groupId: d.get("groupId") }) }); if (!response.ok) return setError("تعذر حفظ التسجيل. راجع البيانات المختارة."); router.push("/dashboard/players"); }
  return <><PageHeader title="تسجيل لاعب جديد" context="اللاعبون / تسجيل لاعب جديد" /><form className="form-shell" onSubmit={e => void submit(e)}><h2>بيانات اللاعب</h2><label>اسم اللاعب بالعربية<input name="playerName" required /></label><label>تاريخ الميلاد<input name="birth" type="date" required /></label><label>النوع<select name="gender" required><option value="1">ذكر</option><option value="2">أنثى</option></select></label><h2>ولي الأمر</h2><label>اسم ولي الأمر<input name="guardianName" required /></label><label>رقم الهاتف<input name="phone" dir="ltr" required /></label><h2>التسجيل الرياضي</h2><label>الفرع<select value={branchId} onChange={e => setBranch(e.target.value)} required><option value="">اختر الفرع</option>{options.branches.map(x => <option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>الرياضة<select value={sportId} onChange={e => setSport(e.target.value)} required><option value="">اختر الرياضة</option>{options.sports.map(x => <option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>الفئة العمرية<select value={categoryId} onChange={e => setCategory(e.target.value)} required><option value="">اختر الفئة</option>{options.categories.map(x => <option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>المجموعة<select name="groupId" required><option value="">اختر المجموعة</option>{groups.map(x => <option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><p className="demo-note">سيُنشأ ملف اللاعب والربط والتسجيل الرياضي فقط؛ لن يُنشأ اشتراك أو تحصيل بعد.</p>{error && <p role="alert" className="error-message">{error}</p>}<div className="form-actions"><button type="submit" className="primary-button">حفظ اللاعب</button><button type="button" onClick={() => router.back()}>إلغاء</button></div></form></>;
}
