using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Academy.Api.Auth;
using Academy.Api.Slice2;
using Academy.Api.Slice5;
using Academy.Api.Slice6;
using Academy.Infrastructure.People;
using Academy.Infrastructure.Persistence;
using Academy.Infrastructure.Structure;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Academy.IntegrationTests;

[Collection("Tenant authentication database")]
public sealed class GuardianCoreIntegrationTests : IAsyncLifetime
{
    private readonly string connection = Environment.GetEnvironmentVariable("ACADEMY_TEST_CONNECTION_STRING") ?? throw new InvalidOperationException("ACADEMY_TEST_CONNECTION_STRING is required.");
    private Factory factory = null!;
    public async Task InitializeAsync() { factory = new Factory(connection); _ = factory.CreateClient(); await CleanupAsync(); }
    public async Task DisposeAsync() { await CleanupAsync(); await factory.DisposeAsync(); }

    [Fact] public async Task Guardian_sees_each_linked_child_once_with_two_sports() { using var c = await Guardian(); var home = await c.GetFromJsonAsync<JsonElement>("/api/v1/guardian/home"); var children = home.GetProperty("children").EnumerateArray().ToArray(); Assert.Equal(children.Length, children.Select(x => x.GetProperty("id").GetGuid()).Distinct().Count()); Assert.Single(children, x => x.GetProperty("id").GetGuid() == Slice2DemoSeed.OmarPlayerId); }
    [Fact] public async Task Child_sports_are_grouped_on_one_card() { using var c = await Guardian(); var home = await c.GetFromJsonAsync<JsonElement>("/api/v1/guardian/home"); var omar = home.GetProperty("children").EnumerateArray().Single(x => x.GetProperty("id").GetGuid() == Slice2DemoSeed.OmarPlayerId); Assert.Equal(2, omar.GetProperty("sports").GetArrayLength()); }
    [Fact] public async Task Guardian_cannot_access_unrelated_child_profile() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OtherPlayerId}/profile")).StatusCode); }
    [Fact] public async Task Guardian_cannot_access_academy_b_child() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/children/{Slice2DemoSeed.AcademyBPlayerId}/profile")).StatusCode); }
    [Fact] public async Task Guardian_profile_exposes_published_evaluations_only() { using var c = await Guardian(); var p = await c.GetFromJsonAsync<JsonElement>($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/profile"); var ids = p.GetProperty("evaluations").EnumerateArray().Select(x => x.GetProperty("id").GetGuid()).ToArray(); Assert.Contains(Slice5DemoSeed.CurrentFootballEvaluationId, ids); Assert.DoesNotContain(Slice5DemoSeed.DraftFootballEvaluationId, ids); }
    [Fact] public async Task Guardian_sees_only_linked_child_attendance() { using var c = await Guardian(); var p = await c.GetFromJsonAsync<JsonElement>($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/profile"); Assert.All(p.GetProperty("attendance").EnumerateArray(), x => Assert.NotEqual("", x.GetProperty("sport").GetString())); }
    [Fact] public async Task Guardian_sees_only_linked_child_subscriptions() { using var c = await Guardian(); var p = await c.GetFromJsonAsync<JsonElement>($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/profile"); Assert.Equal(2, p.GetProperty("enrollments").GetArrayLength()); }
    [Fact] public async Task New_sport_request_for_linked_child_succeeds() { var player = await CreateLinkedPlayer(); using var c = await Guardian(); var r = await Create(c, new { requestType = 1, existingPlayerId = player, sportId = Slice2DemoSeed.SwimmingId, preferredBranchId = Slice2DemoSeed.FifthBranchId }); Assert.Equal(HttpStatusCode.Created, r.StatusCode); }
    [Fact] public async Task New_sport_request_for_unrelated_child_is_rejected() { using var c = await Guardian(); var r = await Create(c, new { requestType = 1, existingPlayerId = Slice2DemoSeed.OtherPlayerId, sportId = Slice2DemoSeed.SwimmingId, preferredBranchId = Slice2DemoSeed.FifthBranchId }); Assert.Equal(HttpStatusCode.NotFound, r.StatusCode); }
    [Fact] public async Task Duplicate_active_request_is_rejected() { using var c = await Guardian(); var r = await Create(c, new { requestType = 1, existingPlayerId = Slice2DemoSeed.OmarPlayerId, sportId = Slice2DemoSeed.BasketballId, preferredBranchId = Slice2DemoSeed.CityBranchId }); Assert.Equal(HttpStatusCode.Conflict, r.StatusCode); }
    [Fact] public async Task Already_enrolled_sport_cannot_be_requested() { using var c = await Guardian(); var r = await Create(c, new { requestType = 1, existingPlayerId = Slice2DemoSeed.OmarPlayerId, sportId = Slice2DemoSeed.FootballId, preferredBranchId = Slice2DemoSeed.CityBranchId }); Assert.Equal(HttpStatusCode.Conflict, r.StatusCode); }
    [Fact] public async Task New_child_request_stores_request_without_player() { var name = $"طفل طلب {Guid.NewGuid():N}"; using var c = await Guardian(); var r = await Create(c, new { requestType = 2, newChildArabicName = name, newChildDateOfBirth = "2019-01-01", sportId = Slice2DemoSeed.FootballId, preferredBranchId = Slice2DemoSeed.CityBranchId }); Assert.Equal(HttpStatusCode.Created, r.StatusCode); await using var s = factory.Services.CreateAsyncScope(); Assert.False(await s.ServiceProvider.GetRequiredService<FoundationDbContext>().Players.AnyAsync(x => x.ArabicName == name)); }
    [Fact] public async Task Request_creation_has_no_financial_effect() { await using var beforeScope = factory.Services.CreateAsyncScope(); var before = await FinancialCounts(beforeScope.ServiceProvider.GetRequiredService<FoundationDbContext>()); using var c = await Guardian(); (await Create(c, new { requestType = 2, newChildArabicName = $"طفل مالي {Guid.NewGuid():N}", newChildDateOfBirth = "2020-01-01", sportId = Slice2DemoSeed.SwimmingId, preferredBranchId = Slice2DemoSeed.FifthBranchId })).EnsureSuccessStatusCode(); await using var afterScope = factory.Services.CreateAsyncScope(); Assert.Equal(before, await FinancialCounts(afterScope.ServiceProvider.GetRequiredService<FoundationDbContext>())); }
    [Fact] public async Task Guardian_sees_only_own_requests() { using var c = await Guardian(); var rows = await c.GetFromJsonAsync<JsonElement>("/api/v1/guardian/enrollment-requests"); Assert.DoesNotContain(rows.EnumerateArray(), x => x.GetProperty("id").GetGuid() == Slice6DemoSeed.AcademyBRequestId); }
    [Fact] public async Task Academy_b_request_is_invisible_to_academy_a_admin() { using var c = await Staff(DemoSeed.AdminEmail); var rows = await c.GetFromJsonAsync<JsonElement>("/api/v1/enrollment-requests"); Assert.DoesNotContain(rows.EnumerateArray(), x => x.GetProperty("id").GetGuid() == Slice6DemoSeed.AcademyBRequestId); }
    [Fact] public async Task Coach_cannot_approve_requests() { using var c = await Staff(DemoSeed.CoachEmail); var r = await Post(c, $"/api/v1/enrollment-requests/{Slice6DemoSeed.PendingRequestId}/approve", new { trainingGroupId = Slice2DemoSeed.FootballGroupId }); Assert.Equal(HttpStatusCode.Forbidden, r.StatusCode); }
    [Fact] public async Task Admin_can_place_request_under_review() { var id = await NewChildRequest(); using var c = await Staff(DemoSeed.AdminEmail); var r = await Post(c, $"/api/v1/enrollment-requests/{id}/review", new { }); Assert.Equal(HttpStatusCode.OK, r.StatusCode); }
    [Fact] public async Task Admin_approval_for_existing_child_creates_one_enrollment() { var setup = await PendingExistingWithGroup(); using var c = await Staff(DemoSeed.AdminEmail); (await Post(c, $"/api/v1/enrollment-requests/{setup.requestId}/approve", new { trainingGroupId = setup.groupId })).EnsureSuccessStatusCode(); await using var s = factory.Services.CreateAsyncScope(); Assert.Equal(1, await s.ServiceProvider.GetRequiredService<FoundationDbContext>().SportEnrollments.CountAsync(x => x.PlayerId == setup.playerId && x.SportId == Slice2DemoSeed.BasketballId)); }
    [Fact] public async Task Repeated_approval_creates_no_duplicate_enrollment() { var setup = await PendingExistingWithGroup(); using var c = await Staff(DemoSeed.AdminEmail); (await Post(c, $"/api/v1/enrollment-requests/{setup.requestId}/approve", new { trainingGroupId = setup.groupId })).EnsureSuccessStatusCode(); (await Post(c, $"/api/v1/enrollment-requests/{setup.requestId}/approve", new { trainingGroupId = setup.groupId })).EnsureSuccessStatusCode(); await using var s = factory.Services.CreateAsyncScope(); Assert.Equal(1, await s.ServiceProvider.GetRequiredService<FoundationDbContext>().SportEnrollments.CountAsync(x => x.PlayerId == setup.playerId && x.SportId == Slice2DemoSeed.BasketballId)); }
    [Fact] public async Task Approval_validates_group_sport_branch_and_tenant() { var player = await CreateLinkedPlayer(); var id = await PendingExisting(player, Slice2DemoSeed.SwimmingId, Slice2DemoSeed.FifthBranchId); using var c = await Staff(DemoSeed.AdminEmail); var r = await Post(c, $"/api/v1/enrollment-requests/{id}/approve", new { trainingGroupId = Slice2DemoSeed.FootballGroupId }); Assert.Equal(HttpStatusCode.UnprocessableEntity, r.StatusCode); }
    [Fact] public async Task New_child_approval_creates_player_link_and_enrollment() { var id = await NewChildRequest(); using var c = await Staff(DemoSeed.AdminEmail); (await Post(c, $"/api/v1/enrollment-requests/{id}/approve", new { trainingGroupId = Slice2DemoSeed.SwimmingGroupId })).EnsureSuccessStatusCode(); await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); var row = await db.NewEnrollmentRequests.SingleAsync(x => x.Id == id); Assert.NotNull(row.ApprovedPlayerId); Assert.True(await db.GuardianPlayerLinks.AnyAsync(x => x.PlayerId == row.ApprovedPlayerId)); Assert.True(await db.SportEnrollments.AnyAsync(x => x.Id == row.CreatedSportEnrollmentId)); }
    [Fact] public async Task Guardian_link_is_not_inferred_from_phone_or_request() { var id = await NewChildRequest(); await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); var row = await db.NewEnrollmentRequests.SingleAsync(x => x.Id == id); Assert.Null(row.ApprovedPlayerId); Assert.False(await db.Players.AnyAsync(x => x.ArabicName == row.NewChildArabicName)); }
    [Fact] public async Task Rejection_preserves_request_and_history() { var id = await NewChildRequest(); using var c = await Staff(DemoSeed.AdminEmail); (await Post(c, $"/api/v1/enrollment-requests/{id}/reject", new { guardianVisibleReason = "العمر غير مناسب للمجموعة الحالية" })).EnsureSuccessStatusCode(); await using var s = factory.Services.CreateAsyncScope(); var row = await s.ServiceProvider.GetRequiredService<FoundationDbContext>().NewEnrollmentRequests.SingleAsync(x => x.Id == id); Assert.Equal(NewEnrollmentRequestStatus.Rejected, row.Status); Assert.NotNull(row.ReviewedAtUtc); }
    [Fact] public async Task Approved_request_points_to_created_enrollment() { var setup = await PendingExistingWithGroup(); using var c = await Staff(DemoSeed.AdminEmail); (await Post(c, $"/api/v1/enrollment-requests/{setup.requestId}/approve", new { trainingGroupId = setup.groupId })).EnsureSuccessStatusCode(); await using var s = factory.Services.CreateAsyncScope(); var row = await s.ServiceProvider.GetRequiredService<FoundationDbContext>().NewEnrollmentRequests.SingleAsync(x => x.Id == setup.requestId); Assert.NotNull(row.CreatedSportEnrollmentId); Assert.Equal(NewEnrollmentRequestStatus.Approved, row.Status); }
    [Fact] public async Task Approved_enrollment_can_enter_existing_subscription_flow() { var id = await NewChildRequest(); using var admin = await Staff(DemoSeed.AdminEmail); var approved = await Post(admin, $"/api/v1/enrollment-requests/{id}/approve", new { trainingGroupId = Slice2DemoSeed.SwimmingGroupId }); var body = await approved.Content.ReadFromJsonAsync<JsonElement>(); using var guardian = await Guardian(); Assert.Equal(HttpStatusCode.OK, (await guardian.GetAsync($"/api/v1/guardian/subscriptions/enrollments/{body.GetProperty("enrollmentId").GetGuid()}/plans")).StatusCode); }
    [Fact] public async Task Child_schedule_exposes_relevant_groups_only() { using var c = await Guardian(); var p = await c.GetFromJsonAsync<JsonElement>($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/profile"); var groups = p.GetProperty("enrollments").EnumerateArray().Select(x => x.GetProperty("group").GetString()).ToArray(); Assert.Contains("ناشئين 2016 — مجموعة أ", groups); Assert.DoesNotContain("براعم 2018 — مجموعة أ", groups); }
    [Fact] public async Task Guardian_cannot_mutate_attendance_or_evaluations() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.Forbidden, (await Put(c, $"/api/v1/attendance/sessions/{Guid.NewGuid()}/players", new { items = Array.Empty<object>() })).StatusCode); Assert.Equal(HttpStatusCode.Forbidden, (await Post(c, $"/api/v1/evaluations/{Slice5DemoSeed.DraftFootballEvaluationId}/publish", new { version = 1 })).StatusCode); }
    [Fact] public async Task Payments_attendance_and_evaluations_regression_endpoints_remain_green() { using var admin = await Staff(DemoSeed.AdminEmail); Assert.Equal(HttpStatusCode.OK, (await admin.GetAsync("/api/v1/subscriptions/collections")).StatusCode); Assert.Equal(HttpStatusCode.OK, (await admin.GetAsync("/api/v1/attendance/sessions")).StatusCode); Assert.Equal(HttpStatusCode.OK, (await admin.GetAsync("/api/v1/evaluations")).StatusCode); }

    private async Task<Guid> NewChildRequest() { using var c = await Guardian(); var r = await Create(c, new { requestType = 2, newChildArabicName = $"طفل جديد {Guid.NewGuid():N}", newChildDateOfBirth = "2019-05-01", sportId = Slice2DemoSeed.SwimmingId, preferredBranchId = Slice2DemoSeed.FifthBranchId }); r.EnsureSuccessStatusCode(); return (await r.Content.ReadFromJsonAsync<Created>())!.Id; }
    private async Task<Guid> PendingExisting(Guid player, Guid sport, Guid branch) { using var c = await Guardian(); var r = await Create(c, new { requestType = 1, existingPlayerId = player, sportId = sport, preferredBranchId = branch }); r.EnsureSuccessStatusCode(); return (await r.Content.ReadFromJsonAsync<Created>())!.Id; }
    private async Task<(Guid requestId, Guid groupId, Guid playerId)> PendingExistingWithGroup() { var player = await CreateLinkedPlayer(); await using var scope = factory.Services.CreateAsyncScope(); var db = scope.ServiceProvider.GetRequiredService<FoundationDbContext>(); var group = new TrainingGroup { Id = Guid.NewGuid(), AcademyId = DemoSeed.NogoomAcademyId, ArabicName = $"سلة طلبات {Guid.NewGuid():N}", BranchId = Slice2DemoSeed.CityBranchId, SportId = Slice2DemoSeed.BasketballId, AgeCategoryId = Slice2DemoSeed.U10Id, CreatedAtUtc = DateTimeOffset.UtcNow, UpdatedAtUtc = DateTimeOffset.UtcNow }; db.TrainingGroups.Add(group); await db.SaveChangesAsync(); return (await PendingExisting(player, Slice2DemoSeed.BasketballId, Slice2DemoSeed.CityBranchId), group.Id, player); }
    private async Task<Guid> CreateLinkedPlayer() { await using var scope = factory.Services.CreateAsyncScope(); var db = scope.ServiceProvider.GetRequiredService<FoundationDbContext>(); var guardian = await db.GuardianProfiles.SingleAsync(x => x.Id == Slice2DemoSeed.MainGuardianId); var player = new Player { Id = Guid.NewGuid(), AcademyId = DemoSeed.NogoomAcademyId, PlayerCode = $"T-{Guid.NewGuid():N}"[..12], ArabicName = $"طفل مرتبط {Guid.NewGuid():N}", DateOfBirth = new DateOnly(2018, 1, 1), CreatedAtUtc = DateTimeOffset.UtcNow, UpdatedAtUtc = DateTimeOffset.UtcNow }; db.Players.Add(player); db.GuardianPlayerLinks.Add(new GuardianPlayerLink { Id = Guid.NewGuid(), AcademyId = DemoSeed.NogoomAcademyId, GuardianId = guardian.Id, PlayerId = player.Id, CreatedByUserId = guardian.UserId, CreatedAtUtc = DateTimeOffset.UtcNow, UpdatedAtUtc = DateTimeOffset.UtcNow }); await db.SaveChangesAsync(); return player.Id; }
    private static async Task<(int collections, int payments, int periods)> FinancialCounts(FoundationDbContext db) => (await db.Collections.CountAsync(), await db.PaymentRequests.CountAsync(), await db.SubscriptionPeriods.CountAsync());
    private async Task<HttpClient> Staff(string email) { var c = factory.CreateClient(); (await Post(c, "/api/v1/auth/login", new { email, password = "Demo-Only-123!" })).EnsureSuccessStatusCode(); return c; }
    private async Task<HttpClient> Guardian() { var c = factory.CreateClient(); var request = await Post(c, "/api/v1/auth/guardian/otp/request", new { phoneNumber = DemoSeed.GuardianPhone }); var challenge = await request.Content.ReadFromJsonAsync<Challenge>(); (await Post(c, "/api/v1/auth/guardian/otp/verify", new { challengeId = challenge!.ChallengeId, phoneNumber = DemoSeed.GuardianPhone, code = "246810" })).EnsureSuccessStatusCode(); return c; }
    private static Task<HttpResponseMessage> Create(HttpClient c, object body) => Send(c, HttpMethod.Post, "/api/v1/guardian/enrollment-requests", body, $"test-slice6-{Guid.NewGuid():N}");
    private static Task<HttpResponseMessage> Post(HttpClient c, string path, object body) => Send(c, HttpMethod.Post, path, body);
    private static Task<HttpResponseMessage> Put(HttpClient c, string path, object body) => Send(c, HttpMethod.Put, path, body);
    private static async Task<HttpResponseMessage> Send(HttpClient c, HttpMethod method, string path, object body, string? key = null) { var request = new HttpRequestMessage(method, path) { Content = JsonContent.Create(body) }; request.Headers.Add("X-CSRF-TOKEN", (await c.GetFromJsonAsync<Csrf>("/api/v1/auth/csrf"))!.Token); if (key is not null) request.Headers.Add("Idempotency-Key", key); return await c.SendAsync(request); }
    private async Task CleanupAsync() { await using var scope = factory.Services.CreateAsyncScope(); var db = scope.ServiceProvider.GetRequiredService<FoundationDbContext>(); await db.NewEnrollmentRequests.Where(x => x.IdempotencyKey.StartsWith("test-slice6-") || x.ExistingPlayer != null && x.ExistingPlayer.PlayerCode.StartsWith("T-") || x.NewChildArabicName != null && (x.NewChildArabicName.StartsWith("طفل جديد") || x.NewChildArabicName.StartsWith("طفل طلب") || x.NewChildArabicName.StartsWith("طفل مالي"))).ExecuteDeleteAsync(); await db.SportEnrollments.Where(x => x.Player.PlayerCode.StartsWith("T-") || x.Player.ArabicName.StartsWith("طفل جديد") || x.Player.ArabicName.StartsWith("طفل طلب") || x.Player.ArabicName.StartsWith("طفل مالي")).ExecuteDeleteAsync(); await db.GuardianPlayerLinks.Where(x => x.Player.PlayerCode.StartsWith("T-") || x.Player.ArabicName.StartsWith("طفل جديد") || x.Player.ArabicName.StartsWith("طفل طلب") || x.Player.ArabicName.StartsWith("طفل مالي")).ExecuteDeleteAsync(); await db.Players.Where(x => x.PlayerCode.StartsWith("T-") || x.ArabicName.StartsWith("طفل جديد") || x.ArabicName.StartsWith("طفل طلب") || x.ArabicName.StartsWith("طفل مالي")).ExecuteDeleteAsync(); await db.TrainingGroups.Where(x => x.ArabicName.StartsWith("سلة طلبات")).ExecuteDeleteAsync(); }
    private sealed record Csrf(string Token); private sealed record Challenge(Guid ChallengeId); private sealed record Created(Guid Id);
    private sealed class Factory(string connection) : WebApplicationFactory<Program> { protected override void ConfigureWebHost(IWebHostBuilder builder) { builder.UseEnvironment("Demo"); builder.UseSetting("ConnectionStrings:Default", connection); builder.UseSetting("Demo:SeedProfile", "LegacyRegression"); builder.UseSetting("Demo:SeedEnabled", "true"); builder.UseSetting("Demo:FixedOtpEnabled", "true"); builder.UseSetting("Demo:FixedOtp", "246810"); builder.UseSetting("Demo:StaffPassword", "Demo-Only-123!"); builder.UseSetting("Demo:ReferenceDate", "2026-09-28"); builder.UseSetting("Payments:InternalTest:Enabled", "true"); builder.UseSetting("Payments:InternalTest:SigningKey", "Demo-Test-Signing-Key-Only-123456"); } }
}
