using System.Net;
using System.Net.Http.Json;
using System.Reflection;
using System.Text.Json;
using Academy.Api.Auth;
using Academy.Api.Slice2;
using Academy.Api.Slice7;
using Academy.Infrastructure.Content;
using Academy.Infrastructure.Persistence;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Academy.IntegrationTests;

[Collection("Tenant authentication database")]
public sealed class Slice7ContentIntegrationTests : IAsyncLifetime
{
    private readonly string connection = Environment.GetEnvironmentVariable("ACADEMY_TEST_CONNECTION_STRING") ?? throw new InvalidOperationException("ACADEMY_TEST_CONNECTION_STRING is required.");
    private Factory factory = null!;
    public async Task InitializeAsync() { factory = new Factory(connection); _ = factory.CreateClient(); await Cleanup(); }
    public async Task DisposeAsync() { await Cleanup(); await factory.DisposeAsync(); }

    [Fact] public async Task Guardian_catalog_deduplicates_sport_sections() { using var c = await Guardian(); var rows = await Get(c, "/api/v1/guardian/catalog"); Assert.Single(rows.EnumerateArray(), x => x.GetProperty("sport").GetString() == "كرة القدم"); }
    [Fact] public async Task Guardian_catalog_contains_only_linked_sports() { using var c = await Guardian(); var rows = await Get(c, "/api/v1/guardian/catalog"); var sports = rows.EnumerateArray().Select(x => x.GetProperty("sport").GetString()).ToArray(); Assert.Contains("كرة القدم", sports); Assert.Contains("السباحة", sports); Assert.DoesNotContain("كرة السلة", sports); }
    [Fact] public async Task Inactive_catalog_item_is_hidden() { using var c = await Guardian(); var json = (await c.GetStringAsync("/api/v1/guardian/catalog")); Assert.DoesNotContain(Slice7DemoSeed.InactiveCatalogId.ToString(), json); }
    [Fact] public async Task Academy_b_catalog_is_hidden() { using var c = await Staff(DemoSeed.AdminEmail); var json = await c.GetStringAsync("/api/v1/content/catalog"); Assert.DoesNotContain("منتج الأكاديمية الثانية", json); }
    [Fact] public async Task Catalog_has_no_cart_or_order_endpoint() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync("/api/v1/guardian/catalog/cart")).StatusCode); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync("/api/v1/guardian/catalog/orders")).StatusCode); }
    [Fact] public async Task Nutrition_has_three_categories() { await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); Assert.Equal(3, await db.NutritionCategoryLinks.Where(x => x.AcademyId == DemoSeed.NogoomAcademyId).Select(x => x.Category).Distinct().CountAsync()); }
    [Fact] public async Task Nutrition_demo_has_exactly_eighteen_placements() { await using var s = factory.Services.CreateAsyncScope(); Assert.Equal(18, await s.ServiceProvider.GetRequiredService<FoundationDbContext>().NutritionCategoryLinks.CountAsync(x => x.AcademyId == DemoSeed.NogoomAcademyId)); }
    [Fact] public async Task Nutrition_demo_has_fifteen_unique_items() { await using var s = factory.Services.CreateAsyncScope(); Assert.Equal(15, await s.ServiceProvider.GetRequiredService<FoundationDbContext>().NutritionItems.CountAsync(x => x.AcademyId == DemoSeed.NogoomAcademyId)); }
    [Fact] public async Task Reusable_meal_appears_in_multiple_categories() { await using var s = factory.Services.CreateAsyncScope(); Assert.Equal(2, await s.ServiceProvider.GetRequiredService<FoundationDbContext>().NutritionCategoryLinks.CountAsync(x => x.NutritionItemId == Slice7DemoSeed.ShakshukaId)); }
    [Fact] public async Task Nutrition_read_has_no_financial_effect() { var before = await Finance(); using var c = await Guardian(); _ = await c.GetAsync("/api/v1/guardian/nutrition?category=Breakfast"); Assert.Equal(before, await Finance()); }
    [Fact] public async Task Nutrition_rejects_negative_values() { using var c = await Staff(DemoSeed.AdminEmail); var r = await Post(c, "/api/v1/content/nutrition", NutritionBody(-1)); Assert.Equal(HttpStatusCode.BadRequest, r.StatusCode); }
    [Fact] public async Task Demo_unreviewed_status_is_exposed() { using var c = await Guardian(); var row = await Get(c, $"/api/v1/guardian/nutrition/{Slice7DemoSeed.ShakshukaId}"); Assert.Equal("DemoUnreviewed", row.GetProperty("dataStatus").GetString()); Assert.Contains("غير صالحة", row.GetProperty("sourceDescription").GetString()); }
    [Fact] public async Task Guardian_can_read_nutrition() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.OK, (await c.GetAsync("/api/v1/guardian/nutrition?category=Dinner")).StatusCode); }
    [Fact] public async Task Nutrition_response_is_not_child_personalized() { using var c = await Guardian(); var json = await c.GetStringAsync($"/api/v1/guardian/nutrition/{Slice7DemoSeed.ShakshukaId}"); Assert.DoesNotContain("playerId", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Admin_can_manage_nutrition_within_academy() { using var c = await Staff(DemoSeed.AdminEmail); var r = await Post(c, "/api/v1/content/nutrition", NutritionBody(140, $"مادة اختبار {Guid.NewGuid():N}")); Assert.Equal(HttpStatusCode.Created, r.StatusCode); }
    [Fact] public async Task Coach_cannot_manage_nutrition() { using var c = await Staff(DemoSeed.CoachEmail); Assert.Equal(HttpStatusCode.Forbidden, (await Post(c, "/api/v1/content/nutrition", NutritionBody(140))).StatusCode); }
    [Fact] public async Task Guardian_sees_published_medical_record() { using var c = await Guardian(); var json = await c.GetStringAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/medical"); Assert.Contains(Slice7DemoSeed.PublishedMedicalId.ToString(), json); }
    [Fact] public async Task Guardian_cannot_see_unpublished_medical_record() { using var c = await Guardian(); var json = await c.GetStringAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/medical"); Assert.DoesNotContain(Slice7DemoSeed.DraftMedicalId.ToString(), json); }
    [Fact] public async Task Guardian_cannot_see_other_child_medical_record() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OtherPlayerId}/medical")).StatusCode); }
    [Fact] public async Task Academy_b_medical_record_is_hidden() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/children/{Slice2DemoSeed.AcademyBPlayerId}/medical")).StatusCode); }
    [Fact] public async Task Coach_has_no_medical_access() { using var c = await Staff(DemoSeed.CoachEmail); Assert.Equal(HttpStatusCode.Forbidden, (await c.GetAsync("/api/v1/medical-records")).StatusCode); }
    [Fact] public async Task Staff_notes_never_leak_to_guardian() { using var c = await Guardian(); var json = await c.GetStringAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/medical"); Assert.DoesNotContain("ملاحظة داخلية", json); Assert.DoesNotContain("staffNotes", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Admin_can_create_update_and_publish_medical_record() { using var c = await Staff(DemoSeed.AdminEmail); var created = await Post(c, "/api/v1/medical-records", MedicalBody(false)); created.EnsureSuccessStatusCode(); var id = (await created.Content.ReadFromJsonAsync<Created>())!.Id; (await Put(c, $"/api/v1/medical-records/{id}", MedicalBody(false, "سجل معدل"))).EnsureSuccessStatusCode(); (await Post(c, $"/api/v1/medical-records/{id}/publication", new { isPublished = true })).EnsureSuccessStatusCode(); await using var s = factory.Services.CreateAsyncScope(); var row = await s.ServiceProvider.GetRequiredService<FoundationDbContext>().PlayerMedicalRecords.SingleAsync(x => x.Id == id); Assert.True(row.IsPublishedToGuardian); Assert.Equal("سجل معدل", row.ArabicTitle); }
    [Fact] public async Task Guardian_sees_published_gallery_media() { using var c = await Guardian(); var json = await c.GetStringAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/media"); Assert.Contains(Slice7DemoSeed.PublishedMediaId.ToString(), json); }
    [Fact] public async Task Guardian_cannot_see_unpublished_media() { using var c = await Guardian(); var json = await c.GetStringAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OmarPlayerId}/media"); Assert.DoesNotContain(Slice7DemoSeed.DraftMediaId.ToString(), json); }
    [Fact] public async Task Guardian_cannot_see_other_child_media() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OtherPlayerId}/media")).StatusCode); }
    [Fact] public async Task Academy_b_media_is_hidden() { using var c = await Guardian(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/children/{Slice2DemoSeed.AcademyBPlayerId}/media")).StatusCode); }
    [Fact] public async Task Arbitrary_media_reference_is_rejected() { using var c = await Staff(DemoSeed.AdminEmail); var r = await Post(c, "/api/v1/player-media", MediaBody("https://example.test/private.jpg")); Assert.Equal(HttpStatusCode.BadRequest, r.StatusCode); }
    [Fact] public async Task Slice7_commands_create_no_financial_records() { var before = await Finance(); using var c = await Staff(DemoSeed.AdminEmail); (await Post(c, "/api/v1/content/catalog", CatalogBody($"منتج اختبار {Guid.NewGuid():N}"))).EnsureSuccessStatusCode(); (await Post(c, "/api/v1/player-media", MediaBody("/demo-assets/gallery-training.svg"))).EnsureSuccessStatusCode(); Assert.Equal(before, await Finance()); }
    [Fact] public async Task Previous_finance_attendance_evaluation_and_enrollment_remain_green() { using var c = await Staff(DemoSeed.AdminEmail); foreach (var path in new[] { "/api/v1/subscriptions/collections", "/api/v1/attendance/sessions", "/api/v1/evaluations", "/api/v1/enrollment-requests" }) Assert.Equal(HttpStatusCode.OK, (await c.GetAsync(path)).StatusCode); }
    [Fact] public void Nutrition_model_has_no_commerce_properties() { var forbidden = new[] { "Price", "Discount", "Rating", "RatingCount", "Quantity", "Cart", "Basket", "Order", "Checkout", "Payment", "Delivery", "Inventory" }; var names = typeof(NutritionItem).GetProperties(BindingFlags.Public | BindingFlags.Instance).Select(x => x.Name).ToArray(); Assert.DoesNotContain(names, x => forbidden.Any(word => x.Contains(word, StringComparison.OrdinalIgnoreCase))); }

    private object NutritionBody(decimal calories, string? name = null) => new { arabicName = name ?? $"مادة اختبار {Guid.NewGuid():N}", arabicDescription = "وصف معلوماتي", imageReference = "/demo-assets/nutrition-meal.svg", servingDescription = "حصة اختبار", calories, proteinGrams = 10, carbohydratesGrams = 20, fatGrams = 5, dataStatus = "DemoUnreviewed", sourceDescription = "للاختبار", categories = new[] { "Breakfast" }, displayOrder = 90, isActive = true };
    private static object MedicalBody(bool published, string title = "سجل طبي اختباري") => new { playerId = Slice2DemoSeed.OmarPlayerId, recordType = "Consultation", arabicTitle = title, recordDate = "2026-09-28", arabicDescription = "وصف اصطناعي للاختبار", status = "Open", staffNotes = "داخلي", guardianVisibleNotes = "ظاهر", isPublishedToGuardian = published };
    private static object MediaBody(string reference) => new { playerId = Slice2DemoSeed.OmarPlayerId, mediaType = "Image", mediaReference = reference, thumbnailReference = (string?)null, arabicCaption = $"test-slice7-{Guid.NewGuid():N}", capturedAtUtc = (string?)null, displayOrder = 90, isPublishedToGuardian = false };
    private static object CatalogBody(string name) => new { sportId = Slice2DemoSeed.FootballId, arabicName = name, englishName = (string?)null, arabicDescription = "عرض فقط", imageReference = "/demo-assets/catalog-football.svg", displayPrice = 100, currency = "EGP", discountPercentage = (decimal?)null, displayOrder = 90, isActive = true };
    private async Task<(int Collections, int Payments, int Periods)> Finance() { await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); return (await db.Collections.CountAsync(), await db.PaymentRequests.CountAsync(), await db.SubscriptionPeriods.CountAsync()); }
    private async Task<HttpClient> Staff(string email) { var c = factory.CreateClient(); (await Post(c, "/api/v1/auth/login", new { email, password = "Demo-Only-123!" })).EnsureSuccessStatusCode(); return c; }
    private async Task<HttpClient> Guardian() { var c = factory.CreateClient(); var request = await Post(c, "/api/v1/auth/guardian/otp/request", new { phoneNumber = DemoSeed.GuardianPhone }); var challenge = await request.Content.ReadFromJsonAsync<Challenge>(); (await Post(c, "/api/v1/auth/guardian/otp/verify", new { challengeId = challenge!.ChallengeId, phoneNumber = DemoSeed.GuardianPhone, code = "246810" })).EnsureSuccessStatusCode(); return c; }
    private static async Task<JsonElement> Get(HttpClient c, string path) => await c.GetFromJsonAsync<JsonElement>(path);
    private static Task<HttpResponseMessage> Post(HttpClient c, string path, object body) => Send(c, HttpMethod.Post, path, body);
    private static Task<HttpResponseMessage> Put(HttpClient c, string path, object body) => Send(c, HttpMethod.Put, path, body);
    private static async Task<HttpResponseMessage> Send(HttpClient c, HttpMethod method, string path, object body) { var request = new HttpRequestMessage(method, path) { Content = JsonContent.Create(body) }; request.Headers.Add("X-CSRF-TOKEN", (await c.GetFromJsonAsync<Csrf>("/api/v1/auth/csrf"))!.Token); return await c.SendAsync(request); }
    private async Task Cleanup() { await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); await db.NutritionItems.Where(x => x.ArabicName.StartsWith("مادة اختبار")).ExecuteDeleteAsync(); await db.SportCatalogItems.Where(x => x.ArabicName.StartsWith("منتج اختبار")).ExecuteDeleteAsync(); await db.PlayerMedicalRecords.Where(x => x.ArabicTitle.StartsWith("سجل طبي اختباري") || x.ArabicTitle == "سجل معدل").ExecuteDeleteAsync(); await db.PlayerMedia.Where(x => x.ArabicCaption != null && x.ArabicCaption.StartsWith("test-slice7-")).ExecuteDeleteAsync(); }
    private sealed record Csrf(string Token); private sealed record Challenge(Guid ChallengeId); private sealed record Created(Guid Id);
    private sealed class Factory(string connection) : WebApplicationFactory<Program> { protected override void ConfigureWebHost(IWebHostBuilder builder) { builder.UseEnvironment("Demo"); builder.UseSetting("ConnectionStrings:Default", connection); builder.UseSetting("Demo:SeedEnabled", "true"); builder.UseSetting("Demo:FixedOtpEnabled", "true"); builder.UseSetting("Demo:FixedOtp", "246810"); builder.UseSetting("Demo:StaffPassword", "Demo-Only-123!"); builder.UseSetting("Demo:ReferenceDate", "2026-09-28"); builder.UseSetting("Payments:InternalTest:Enabled", "true"); builder.UseSetting("Payments:InternalTest:SigningKey", "Demo-Test-Signing-Key-Only-123456"); } }
}
