using System.Net;
using System.Net.Http.Json;
using Academy.Api.Auth;
using Academy.Api.Slice2;
using Academy.Infrastructure.People;
using Academy.Infrastructure.Persistence;
using Academy.Infrastructure.Structure;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Academy.IntegrationTests;

[Collection("Tenant authentication database")]
public sealed class StructurePeopleEnrollmentTests : IAsyncLifetime
{
    private readonly string connection = Environment.GetEnvironmentVariable("ACADEMY_TEST_CONNECTION_STRING") ?? throw new InvalidOperationException("ACADEMY_TEST_CONNECTION_STRING is required.");
    private Factory factory = null!;
    public Task InitializeAsync() { factory = new Factory(connection); _ = factory.CreateClient(); return Task.CompletedTask; }
    public async Task DisposeAsync() => await factory.DisposeAsync();

    [Fact] public async Task Owner_can_create_structure_in_own_academy() { using var c = factory.CreateClient(); await Login(c, DemoSeed.OwnerEmail); var token = await Csrf(c); var name = $"فرع اختبار {Guid.NewGuid():N}"; var r = await Post(c, "/api/v1/manage/branches", new { arabicName = name }, token); Assert.Equal(HttpStatusCode.Created, r.StatusCode); await using var s = factory.Services.CreateAsyncScope(); Assert.True(await s.ServiceProvider.GetRequiredService<FoundationDbContext>().Branches.AnyAsync(x => x.AcademyId == DemoSeed.NogoomAcademyId && x.ArabicName == name)); }
    [Theory] [InlineData(DemoSeed.CoachEmail)] public async Task Coach_cannot_administer_structure(string email) { using var c = factory.CreateClient(); await Login(c, email); var r = await Post(c, "/api/v1/manage/branches", new { arabicName = "ممنوع" }, await Csrf(c)); Assert.Equal(HttpStatusCode.Forbidden, r.StatusCode); }
    [Fact] public async Task Guardian_cannot_administer_structure() { using var c = factory.CreateClient(); await GuardianLogin(c, DemoSeed.GuardianPhone); var r = await Post(c, "/api/v1/manage/branches", new { arabicName = "ممنوع" }, await Csrf(c)); Assert.Equal(HttpStatusCode.Forbidden, r.StatusCode); }
    [Fact] public async Task Cross_tenant_structure_references_are_rejected() { using var c = factory.CreateClient(); await Login(c, DemoSeed.OwnerEmail); var options = await OptionsB(); var r = await Post(c, "/api/v1/manage/groups", new { arabicName = "خلط مرفوض", branchId = options.branch, sportId = Slice2DemoSeed.FootballId, ageCategoryId = Slice2DemoSeed.U10Id }, await Csrf(c)); Assert.Equal(HttpStatusCode.UnprocessableEntity, r.StatusCode); }
    [Fact] public async Task Player_persists_after_reload() { await using var s1 = factory.Services.CreateAsyncScope(); Assert.True(await s1.ServiceProvider.GetRequiredService<FoundationDbContext>().Players.AnyAsync(x => x.Id == Slice2DemoSeed.OmarPlayerId)); await using var s2 = factory.Services.CreateAsyncScope(); Assert.Equal("عمر أحمد محمود", await s2.ServiceProvider.GetRequiredService<FoundationDbContext>().Players.Where(x => x.Id == Slice2DemoSeed.OmarPlayerId).Select(x => x.ArabicName).SingleAsync()); }
    [Fact] public async Task Guardian_link_is_explicit_and_persistent() { await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); Assert.True(await db.GuardianPlayerLinks.AnyAsync(x => x.GuardianId == Slice2DemoSeed.MainGuardianId && x.PlayerId == Slice2DemoSeed.OmarPlayerId)); }
    [Fact] public async Task Guardian_with_two_children_sees_only_both() { using var c = factory.CreateClient(); await GuardianLogin(c, DemoSeed.GuardianPhone); var children = await c.GetFromJsonAsync<List<Child>>("/api/v1/guardian/children"); Assert.Equal(2, children!.Count); Assert.DoesNotContain(children, x => x.Id == Slice2DemoSeed.OtherPlayerId || x.Id == Slice2DemoSeed.AcademyBPlayerId); }
    [Fact] public async Task Same_player_has_football_and_swimming_enrollments() { await using var s = factory.Services.CreateAsyncScope(); var sports = await s.ServiceProvider.GetRequiredService<FoundationDbContext>().SportEnrollments.Where(x => x.PlayerId == Slice2DemoSeed.OmarPlayerId).Select(x => x.SportId).ToListAsync(); Assert.Contains(Slice2DemoSeed.FootballId, sports); Assert.Contains(Slice2DemoSeed.SwimmingId, sports); }
    [Fact] public async Task Multiple_sports_do_not_duplicate_player() { await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); Assert.Equal(1, await db.Players.CountAsync(x => x.Id == Slice2DemoSeed.OmarPlayerId)); Assert.Equal(2, await db.SportEnrollments.CountAsync(x => x.PlayerId == Slice2DemoSeed.OmarPlayerId)); }
    [Fact] public async Task Adding_sport_reuses_existing_player_guardian_and_link() { using var c = factory.CreateClient(); await Login(c, DemoSeed.OwnerEmail); var suffix = Guid.NewGuid().ToString("N")[..8]; var phone = $"+2011{Random.Shared.Next(10_000_000, 99_999_999)}"; var first = await Post(c, "/api/v1/people/registrations", new { playerArabicName = $"لاعب تعدد {suffix}", dateOfBirth = "2016-01-01", gender = 1, guardianName = $"ولي تعدد {suffix}", guardianPhone = phone, branchId = Slice2DemoSeed.CityBranchId, sportId = Slice2DemoSeed.FootballId, groupId = Slice2DemoSeed.FootballGroupId }, await Csrf(c)); first.EnsureSuccessStatusCode(); var created = await first.Content.ReadFromJsonAsync<RegistrationResult>(); await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); var guardianId = await db.GuardianProfiles.Where(x => x.AcademyId == DemoSeed.NogoomAcademyId && x.ContactPhone == phone).Select(x => x.Id).SingleAsync(); var basketballGroupId = Guid.NewGuid(); db.TrainingGroups.Add(new TrainingGroup { Id = basketballGroupId, AcademyId = DemoSeed.NogoomAcademyId, ArabicName = $"سلة اختبار {suffix}", BranchId = Slice2DemoSeed.CityBranchId, SportId = Slice2DemoSeed.BasketballId, AgeCategoryId = Slice2DemoSeed.U10Id, CreatedAtUtc = DateTimeOffset.UtcNow, UpdatedAtUtc = DateTimeOffset.UtcNow }); await db.SaveChangesAsync(); var second = await Post(c, "/api/v1/people/registrations", new { existingPlayerId = created!.PlayerId, existingGuardianId = guardianId, branchId = Slice2DemoSeed.CityBranchId, sportId = Slice2DemoSeed.BasketballId, groupId = basketballGroupId }, await Csrf(c)); Assert.Equal(HttpStatusCode.Created, second.StatusCode); Assert.Equal(1, await db.Players.CountAsync(x => x.Id == created.PlayerId)); Assert.Equal(2, await db.SportEnrollments.CountAsync(x => x.PlayerId == created.PlayerId)); Assert.Equal(1, await db.GuardianPlayerLinks.CountAsync(x => x.PlayerId == created.PlayerId && x.GuardianId == guardianId)); }
    [Fact] public async Task Invalid_group_sport_mismatch_is_rejected() { using var c = factory.CreateClient(); await Login(c, DemoSeed.OwnerEmail); var r = await Post(c, "/api/v1/people/registrations", new { playerArabicName = "لاعب معاملة فاشلة", dateOfBirth = "2016-01-01", gender = 1, guardianName = "ولي معاملة فاشلة", guardianPhone = "+201099999991", branchId = Slice2DemoSeed.CityBranchId, sportId = Slice2DemoSeed.SwimmingId, groupId = Slice2DemoSeed.FootballGroupId }, await Csrf(c)); Assert.Equal(HttpStatusCode.UnprocessableEntity, r.StatusCode); await using var s = factory.Services.CreateAsyncScope(); Assert.False(await s.ServiceProvider.GetRequiredService<FoundationDbContext>().Players.AnyAsync(x => x.ArabicName == "لاعب معاملة فاشلة")); }
    [Fact] public async Task Duplicate_active_guardian_link_is_rejected_by_database() { await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); db.GuardianPlayerLinks.Add(new GuardianPlayerLink { Id = Guid.NewGuid(), AcademyId = DemoSeed.NogoomAcademyId, GuardianId = Slice2DemoSeed.MainGuardianId, PlayerId = Slice2DemoSeed.OmarPlayerId, CreatedByUserId = Guid.NewGuid(), IsActive = true, CreatedAtUtc = DateTimeOffset.UtcNow, UpdatedAtUtc = DateTimeOffset.UtcNow }); await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync()); }
    [Fact] public async Task Coach_assignment_rejects_cross_tenant_group() { using var c = factory.CreateClient(); await Login(c, DemoSeed.OwnerEmail); await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); var coach = await db.AcademyMemberships.SingleAsync(x => x.AcademyId == DemoSeed.NogoomAcademyId && x.Role == Infrastructure.Tenancy.AcademyRole.Coach); var bGroup = await db.TrainingGroups.Where(x => x.AcademyId == DemoSeed.FutureAcademyId).Select(x => x.Id).FirstAsync(); var r = await Post(c, $"/api/v1/manage/groups/{bGroup}/coaches", new { membershipId = coach.Id }, await Csrf(c)); Assert.Equal(HttpStatusCode.UnprocessableEntity, r.StatusCode); }
    [Fact] public async Task Academy_A_search_cannot_read_Academy_B_players() { using var c = factory.CreateClient(); await Login(c, DemoSeed.OwnerEmail); var players = await c.GetFromJsonAsync<List<PlayerResult>>("/api/v1/people/players?search=عمر"); Assert.DoesNotContain(players!, x => x.Id == Slice2DemoSeed.AcademyBPlayerId); }
    [Fact] public async Task Group_filter_returns_only_group_players() { using var c = factory.CreateClient(); await Login(c, DemoSeed.OwnerEmail); var players = await c.GetFromJsonAsync<List<PlayerResult>>($"/api/v1/people/players?groupId={Slice2DemoSeed.SwimmingGroupId}"); Assert.Single(players!); Assert.Equal(Slice2DemoSeed.OmarPlayerId, players![0].Id); }
    [Fact] public async Task Guardian_cannot_change_id_to_access_another_child() { using var c = factory.CreateClient(); await GuardianLogin(c, DemoSeed.GuardianPhone); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/children/{Slice2DemoSeed.OtherPlayerId}")).StatusCode); }
    [Fact] public async Task Slice2_seed_rerun_is_idempotent() { var before = await Counts(); await DemoSeed.SeedAsync(factory.Services); await DemoSeed.SeedAsync(factory.Services); Assert.Equal(before, await Counts()); }
    [Fact] public async Task Academy_B_seed_remains_isolated() { await using var s = factory.Services.CreateAsyncScope(); var db = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); Assert.True(await db.Players.AnyAsync(x => x.AcademyId == DemoSeed.FutureAcademyId && x.Id == Slice2DemoSeed.AcademyBPlayerId)); Assert.False(await db.GuardianPlayerLinks.AnyAsync(x => x.AcademyId == DemoSeed.NogoomAcademyId && x.PlayerId == Slice2DemoSeed.AcademyBPlayerId)); }

    private async Task<(int,int,int,int)> Counts() { await using var s = factory.Services.CreateAsyncScope(); var d = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); return (await d.Branches.CountAsync(), await d.Players.CountAsync(), await d.GuardianPlayerLinks.CountAsync(), await d.SportEnrollments.CountAsync()); }
    private async Task<(Guid branch, Guid sport, Guid group)> OptionsB() { await using var s = factory.Services.CreateAsyncScope(); var d = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); return (await d.Branches.Where(x => x.AcademyId == DemoSeed.FutureAcademyId).Select(x => x.Id).FirstAsync(), await d.Sports.Where(x => x.AcademyId == DemoSeed.FutureAcademyId).Select(x => x.Id).FirstAsync(), await d.TrainingGroups.Where(x => x.AcademyId == DemoSeed.FutureAcademyId).Select(x => x.Id).FirstAsync()); }
    private static async Task Login(HttpClient c, string email) { var r = await Post(c, "/api/v1/auth/login", new { email, password = "Demo-Only-123!" }, await Csrf(c)); r.EnsureSuccessStatusCode(); }
    private static async Task GuardianLogin(HttpClient c, string phone) { var request = await Post(c, "/api/v1/auth/guardian/otp/request", new { phoneNumber = phone }, await Csrf(c)); var challenge = await request.Content.ReadFromJsonAsync<Challenge>(); var verify = await Post(c, "/api/v1/auth/guardian/otp/verify", new { challengeId = challenge!.ChallengeId, phoneNumber = phone, code = "246810" }, await Csrf(c)); verify.EnsureSuccessStatusCode(); }
    private static async Task<string> Csrf(HttpClient c) => (await c.GetFromJsonAsync<CsrfToken>("/api/v1/auth/csrf"))!.Token;
    private static Task<HttpResponseMessage> Post(HttpClient c, string path, object body, string token) { var request = new HttpRequestMessage(HttpMethod.Post, path) { Content = JsonContent.Create(body) }; request.Headers.Add("X-CSRF-TOKEN", token); return c.SendAsync(request); }
    private sealed record CsrfToken(string Token); private sealed record Challenge(Guid ChallengeId); private sealed record Child(Guid Id); private sealed record PlayerResult(Guid Id); private sealed record RegistrationResult(Guid PlayerId);
    private sealed class Factory(string connection) : WebApplicationFactory<Program> { protected override void ConfigureWebHost(IWebHostBuilder builder) { builder.UseEnvironment("Demo"); builder.UseSetting("ConnectionStrings:Default", connection); builder.UseSetting("Demo:SeedProfile", "LegacyRegression"); builder.UseSetting("Demo:SeedEnabled", "true"); builder.UseSetting("Demo:FixedOtpEnabled", "true"); builder.UseSetting("Demo:FixedOtp", "246810"); builder.UseSetting("Demo:StaffPassword", "Demo-Only-123!"); } }
}
