using System.Net;
using System.Net.Http.Json;
using Academy.Api.Auth;
using Academy.Api.Slice2;
using Academy.Api.Slice3;
using Academy.Infrastructure.Persistence;
using Academy.Infrastructure.Subscriptions;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Academy.IntegrationTests;

[Collection("Tenant authentication database")]
public sealed class SubscriptionPaymentTests : IAsyncLifetime
{
    private readonly string connection = Environment.GetEnvironmentVariable("ACADEMY_TEST_CONNECTION_STRING") ?? throw new InvalidOperationException("ACADEMY_TEST_CONNECTION_STRING is required.");
    private Factory factory = null!;
    public Task InitializeAsync() { factory = new Factory(connection); _ = factory.CreateClient(); return Task.CompletedTask; }
    public async Task DisposeAsync() => await factory.DisposeAsync();

    [Fact] public async Task Payment_success_creates_exactly_one_collection() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Success"); Assert.Equal(1, await Count<PaymentCollection>(x => x.PaymentRequestId == p)); }
    [Fact] public async Task Duplicate_success_callback_still_creates_one_collection() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Success"); await Simulate(p, "Success"); Assert.Equal(1, await Count<PaymentCollection>(x => x.PaymentRequestId == p)); }
    [Fact] public async Task Duplicate_callback_creates_one_receipt() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Success"); await Simulate(p, "Success"); Assert.Equal(1, await Count<Receipt>(x => x.Collection.PaymentRequestId == p)); }
    [Fact] public async Task Duplicate_callback_creates_one_period() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Success"); await Simulate(p, "Success"); Assert.Equal(1, await Count<SubscriptionPeriod>(x => x.Collection.PaymentRequestId == p)); }
    [Fact] public async Task Failed_payment_creates_no_collection() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Failed"); Assert.Equal(0, await Count<PaymentCollection>(x => x.PaymentRequestId == p)); }
    [Fact] public async Task Cancelled_payment_creates_no_collection() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Cancelled"); Assert.Equal(0, await Count<PaymentCollection>(x => x.PaymentRequestId == p)); }
    [Fact] public async Task Failed_payment_does_not_extend_subscription() { var enrollment = await Enrollment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); var before = await Count<SubscriptionPeriod>(x => x.SportEnrollmentId == enrollment); var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Failed"); Assert.Equal(before, await Count<SubscriptionPeriod>(x => x.SportEnrollmentId == enrollment)); }
    [Fact] public async Task Early_renewal_starts_after_existing_end() { var enrollment = await Enrollment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); DateOnly priorEnd; await using (var s = factory.Services.CreateAsyncScope()) { priorEnd = (await s.ServiceProvider.GetRequiredService<FoundationDbContext>().SubscriptionPeriods.Where(x => x.SportEnrollmentId == enrollment && x.Status != SubscriptionPeriodStatus.Cancelled && x.EndDate != null).MaxAsync(x => x.EndDate))!.Value; } var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Success"); await using var verify = factory.Services.CreateAsyncScope(); var period = await verify.ServiceProvider.GetRequiredService<FoundationDbContext>().SubscriptionPeriods.SingleAsync(x => x.Collection.PaymentRequestId == p); Assert.Equal(priorEnd.AddDays(1), period.StartDate); }
    [Fact] public async Task Expired_renewal_starts_on_reference_date() { var enrollment = await Enrollment(Slice2DemoSeed.MariamPlayerId, Slice2DemoSeed.FootballId); await using var setup = factory.Services.CreateAsyncScope(); var db = setup.ServiceProvider.GetRequiredService<FoundationDbContext>(); var future = await db.SubscriptionPeriods.Where(x => x.SportEnrollmentId == enrollment && x.EndDate >= new DateOnly(2026, 9, 28) && x.Status != SubscriptionPeriodStatus.Cancelled).ToListAsync(); var states = future.Select(x => (x, x.Status)).ToList(); foreach (var item in future) item.Status = SubscriptionPeriodStatus.Cancelled; await db.SaveChangesAsync(); try { var p = await NewPayment(Slice2DemoSeed.MariamPlayerId, Slice2DemoSeed.FootballId); await Simulate(p, "Success"); await using var verify = factory.Services.CreateAsyncScope(); Assert.Equal(new DateOnly(2026, 9, 28), await verify.ServiceProvider.GetRequiredService<FoundationDbContext>().SubscriptionPeriods.Where(x => x.Collection.PaymentRequestId == p).Select(x => x.StartDate).SingleAsync()); } finally { foreach (var (item, status) in states) item.Status = status; await db.SaveChangesAsync(); } }
    [Fact] public async Task Cross_tenant_payment_request_access_is_rejected() { using var c = await GuardianClient(); Assert.Equal(HttpStatusCode.NotFound, (await c.GetAsync($"/api/v1/guardian/subscriptions/payments/{Guid.NewGuid()}")).StatusCode); }
    [Fact] public async Task Guardian_cannot_renew_unrelated_player() { var enrollment = await Enrollment(Slice2DemoSeed.OtherPlayerId, Slice2DemoSeed.FootballId); using var c = await GuardianClient(); var r = await Post(c, "/api/v1/guardian/subscriptions/renewals", new { sportEnrollmentId = enrollment, subscriptionPlanId = Slice3DemoSeed.FootballMonthlyId }, await Csrf(c), Guid.NewGuid().ToString()); Assert.Equal(HttpStatusCode.NotFound, r.StatusCode); }
    [Fact] public async Task Wrong_amount_callback_is_rejected() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); ProviderEventEnvelope e; await using (var s = factory.Services.CreateAsyncScope()) { var d = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); var gateway = s.ServiceProvider.GetRequiredService<IPaymentGateway>(); e = gateway.CreateTestEvent(await d.PaymentRequests.SingleAsync(x => x.Id == p), PaymentEventOutcome.Success); } e = e with { Amount = e.Amount + 1 }; using var c = factory.CreateClient(); var r = await c.PostAsJsonAsync("/api/v1/payments/internal-test/events", e); Assert.Equal(HttpStatusCode.BadRequest, r.StatusCode); Assert.Equal(0, await Count<PaymentCollection>(x => x.PaymentRequestId == p)); }
    [Fact] public async Task Provider_event_id_replay_is_idempotent() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); ProviderEventEnvelope e; await using (var s = factory.Services.CreateAsyncScope()) { var d = s.ServiceProvider.GetRequiredService<FoundationDbContext>(); e = s.ServiceProvider.GetRequiredService<IPaymentGateway>().CreateTestEvent(await d.PaymentRequests.SingleAsync(x => x.Id == p), PaymentEventOutcome.Success); } using var c = factory.CreateClient(); (await c.PostAsJsonAsync("/api/v1/payments/internal-test/events", e)).EnsureSuccessStatusCode(); (await c.PostAsJsonAsync("/api/v1/payments/internal-test/events", e)).EnsureSuccessStatusCode(); Assert.Equal(1, await Count<PaymentProviderEvent>(x => x.ProviderEventId == e.ProviderEventId)); }
    [Fact] public void Internal_gateway_is_refused_outside_demo_test() { var env = new StubEnvironment { EnvironmentName = Environments.Production }; Assert.Throws<InvalidOperationException>(() => InternalTestPaymentGateway.ValidateEnvironment(env, new InternalTestPaymentOptions { Enabled = true, SigningKey = "long-enough-test-signing-key" })); }
    [Fact] public async Task Collection_total_uses_confirmed_records_only() { using var c = factory.CreateClient(); await StaffLogin(c); var result = await c.GetFromJsonAsync<CollectionResult>("/api/v1/subscriptions/collections"); await using var s = factory.Services.CreateAsyncScope(); var expected = await s.ServiceProvider.GetRequiredService<FoundationDbContext>().Collections.Where(x => x.AcademyId == DemoSeed.NogoomAcademyId).SumAsync(x => x.Amount); Assert.Equal(expected, result!.Total); }
    [Fact] public async Task Plan_validation_rejects_invalid_combinations() { using var c = factory.CreateClient(); await StaffLogin(c); var r = await Post(c, "/api/v1/subscriptions/plans", new { arabicName = "غير صالح", sportId = Slice2DemoSeed.FootballId, planType = 1, price = 1, durationDays = (int?)null, sessionCount = 2 }, await Csrf(c)); Assert.Equal(HttpStatusCode.BadRequest, r.StatusCode); }
    [Fact] public async Task Client_cannot_override_plan_amount_or_currency() { using var c = await GuardianClient(); var enrollment = await Enrollment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); var r = await Post(c, "/api/v1/guardian/subscriptions/renewals", new { sportEnrollmentId = enrollment, subscriptionPlanId = Slice3DemoSeed.FootballMonthlyId, amount = .01m, currency = "USD" }, await Csrf(c), Guid.NewGuid().ToString()); var created = await r.Content.ReadFromJsonAsync<Created>(); await using var s = factory.Services.CreateAsyncScope(); var payment = await s.ServiceProvider.GetRequiredService<FoundationDbContext>().PaymentRequests.SingleAsync(x => x.Id == created!.PaymentId); Assert.Equal(900m, payment.Amount); Assert.Equal("EGP", payment.Currency); }
    [Fact] public async Task Browser_return_query_cannot_confirm_payment() { var p = await NewPayment(Slice2DemoSeed.OmarPlayerId, Slice2DemoSeed.FootballId); using var c = await GuardianClient(); var r = await c.GetFromJsonAsync<PaymentStatus>($"/api/v1/guardian/subscriptions/payments/{p}?success=true"); Assert.Equal("Pending", r!.Status); Assert.Equal(0, await Count<PaymentCollection>(x => x.PaymentRequestId == p)); }

    private async Task<Guid> NewPayment(Guid player, Guid sport) { using var c = await GuardianClient(); var enrollment = await Enrollment(player, sport); var plan = sport == Slice2DemoSeed.SwimmingId ? Slice3DemoSeed.SwimmingMonthlyId : Slice3DemoSeed.FootballMonthlyId; var r = await Post(c, "/api/v1/guardian/subscriptions/renewals", new { sportEnrollmentId = enrollment, subscriptionPlanId = plan }, await Csrf(c), Guid.NewGuid().ToString()); r.EnsureSuccessStatusCode(); return (await r.Content.ReadFromJsonAsync<Created>())!.PaymentId; }
    private async Task Simulate(Guid payment, string outcome) { using var c = await GuardianClient(); (await Post(c, $"/api/v1/guardian/subscriptions/payments/{payment}/simulate", new { outcome }, await Csrf(c))).EnsureSuccessStatusCode(); }
    private async Task<HttpClient> GuardianClient() { var c = factory.CreateClient(); var request = await Post(c, "/api/v1/auth/guardian/otp/request", new { phoneNumber = DemoSeed.GuardianPhone }, await Csrf(c)); var challenge = await request.Content.ReadFromJsonAsync<Challenge>(); (await Post(c, "/api/v1/auth/guardian/otp/verify", new { challengeId = challenge!.ChallengeId, phoneNumber = DemoSeed.GuardianPhone, code = "246810" }, await Csrf(c))).EnsureSuccessStatusCode(); return c; }
    private async Task StaffLogin(HttpClient c) { (await Post(c, "/api/v1/auth/login", new { email = DemoSeed.OwnerEmail, password = "Demo-Only-123!" }, await Csrf(c))).EnsureSuccessStatusCode(); }
    private async Task<Guid> Enrollment(Guid player, Guid sport) { await using var s = factory.Services.CreateAsyncScope(); return await s.ServiceProvider.GetRequiredService<FoundationDbContext>().SportEnrollments.Where(x => x.PlayerId == player && x.SportId == sport).Select(x => x.Id).SingleAsync(); }
    private async Task<int> Count<T>(System.Linq.Expressions.Expression<Func<T, bool>> predicate) where T : class { await using var s = factory.Services.CreateAsyncScope(); return await s.ServiceProvider.GetRequiredService<FoundationDbContext>().Set<T>().CountAsync(predicate); }
    private static async Task<string> Csrf(HttpClient c) => (await c.GetFromJsonAsync<CsrfDto>("/api/v1/auth/csrf"))!.Token;
    private static Task<HttpResponseMessage> Post(HttpClient c, string path, object body, string token, string? key = null) { var r = new HttpRequestMessage(HttpMethod.Post, path) { Content = JsonContent.Create(body) }; r.Headers.Add("X-CSRF-TOKEN", token); if (key is not null) r.Headers.Add("Idempotency-Key", key); return c.SendAsync(r); }
    private sealed record CsrfDto(string Token); private sealed record Challenge(Guid ChallengeId); private sealed record Created(Guid PaymentId); private sealed record PaymentStatus(string Status); private sealed record CollectionResult(decimal Total);
    private sealed class Factory(string connection) : WebApplicationFactory<Program> { protected override void ConfigureWebHost(IWebHostBuilder b) { b.UseEnvironment("Demo"); b.UseSetting("ConnectionStrings:Default", connection); b.UseSetting("Demo:SeedEnabled", "true"); b.UseSetting("Demo:FixedOtpEnabled", "true"); b.UseSetting("Demo:FixedOtp", "246810"); b.UseSetting("Demo:StaffPassword", "Demo-Only-123!"); b.UseSetting("Demo:ReferenceDate", "2026-09-28"); b.UseSetting("Payments:InternalTest:Enabled", "true"); b.UseSetting("Payments:InternalTest:SigningKey", "Demo-Test-Signing-Key-Only-123456"); } }
    private sealed class StubEnvironment : IHostEnvironment { public string EnvironmentName { get; set; } = Environments.Production; public string ApplicationName { get; set; } = "Tests"; public string ContentRootPath { get; set; } = string.Empty; public Microsoft.Extensions.FileProviders.IFileProvider ContentRootFileProvider { get; set; } = null!; }
}
