"use client";
import { FormEvent, use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "../../../../../components/dashboard-shell";
type Item = { id: string; arabicName: string; branchId?: string; sportId?: string; ageCategoryId?: string };
type Options = { branches: Item[]; sports: Item[]; categories: Item[]; groups: Item[]; coaches: Item[] };
const titles: Record<string,string> = { branches: "إضافة فرع", sports: "إضافة رياضة", categories: "إضافة فئة عمرية", groups: "إنشاء مجموعة", coaches: "إسناد مدرب" };
export default function NewStructurePage({ params }: { params: Promise<{ kind: string }> }) { const { kind } = use(params); const router = useRouter(); const [options,setOptions] = useState<Options>({ branches:[],sports:[],categories:[],groups:[],coaches:[] }); const [error,setError]=useState(""); useEffect(()=>{ fetch("/api/v1/manage/structure/options").then(r=>r.json()).then(setOptions); },[]); async function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); const d=new FormData(e.currentTarget); const csrf=await fetch("/api/v1/auth/csrf").then(r=>r.json()) as {token:string}; let path=`/api/v1/manage/${kind === "categories" ? "age-categories" : kind}`; let body:Record<string,unknown>={arabicName:d.get("arabicName")}; if(kind==="branches") body.description=d.get("description"); if(kind==="categories"){body.minimumBirthYear=Number(d.get("min"))||null;body.maximumBirthYear=Number(d.get("max"))||null;} if(kind==="groups") body={...body,branchId:d.get("branchId"),sportId:d.get("sportId"),ageCategoryId:d.get("categoryId"),capacity:Number(d.get("capacity"))||null}; if(kind==="coaches"){path=`/api/v1/manage/groups/${d.get("groupId")}/coaches`;body={membershipId:d.get("membershipId")};} const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-TOKEN":csrf.token},body:JSON.stringify(body)}); if(!r.ok)return setError("تعذر الحفظ. راجع البيانات المختارة."); router.push(`/dashboard/academy/${kind}`); }
  return <><PageHeader title={titles[kind] ?? "إضافة سجل"} context={`الأكاديمية / ${titles[kind] ?? "إضافة"}`} /><form className="form-shell" onSubmit={e=>void submit(e)}>{kind!=="coaches"&&<label>الاسم بالعربية<input name="arabicName" required /></label>}{kind==="branches"&&<label>العنوان المختصر<input name="description" /></label>}{kind==="categories"&&<><label>أقل سنة ميلاد<input name="min" type="number" /></label><label>أعلى سنة ميلاد<input name="max" type="number" /></label></>}{kind==="groups"&&<><label>الفرع<select name="branchId" required>{options.branches.map(x=><option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>الرياضة<select name="sportId" required>{options.sports.map(x=><option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>الفئة العمرية<select name="categoryId" required>{options.categories.map(x=><option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>السعة الاختيارية<input name="capacity" type="number" min="1" /></label></>}{kind==="coaches"&&<><label>المدرب<select name="membershipId" required>{options.coaches.map(x=><option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>المجموعة<select name="groupId" required>{options.groups.map(x=><option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label></>}{error&&<p role="alert" className="error-message">{error}</p>}<div className="form-actions"><button className="primary-button">حفظ</button><button type="button" onClick={()=>router.back()}>إلغاء</button></div></form></>;
}
