// <auto-generated />
using System;
using Academy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Academy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FoundationDbContext))]
    [Migration("20260928205223_Slice4TrainingSessionsAttendance")]
    partial class Slice4TrainingSessionsAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Academy.Infrastructure.Attendance.PlayerAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsumedSubscriptionPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TrainingGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "ConsumedSubscriptionPeriodId");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "SportEnrollmentId", "TrainingGroupId");

                    b.HasIndex("AcademyId", "TrainingSessionId", "SportEnrollmentId")
                        .IsUnique();

                    b.HasIndex("AcademyId", "TrainingSessionId", "TrainingGroupId");

                    b.ToTable("PlayerAttendances", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Attendance.StaffAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TrainingGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "AcademyMembershipId", "TrainingGroupId");

                    b.HasIndex("AcademyId", "TrainingSessionId", "AcademyMembershipId")
                        .IsUnique();

                    b.HasIndex("AcademyId", "TrainingSessionId", "TrainingGroupId");

                    b.ToTable("StaffAttendances", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Attendance.SubscriptionSessionMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerAttendanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReversesMovementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "ReversesMovementId")
                        .IsUnique()
                        .HasFilter("\"ReversesMovementId\" IS NOT NULL");

                    b.HasIndex("AcademyId", "SubscriptionPeriodId");

                    b.HasIndex("AcademyId", "PlayerAttendanceId", "OccurredAtUtc");

                    b.ToTable("SubscriptionSessionMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionSessionMovements_Balance", "\"BalanceBefore\" >= 0 AND \"BalanceAfter\" >= 0");

                            t.HasCheckConstraint("CK_SubscriptionSessionMovements_Quantity", "(\"MovementType\" = 'AttendanceConsume' AND \"Quantity\" = -1 AND \"BalanceAfter\" = \"BalanceBefore\" - 1) OR (\"MovementType\" = 'AttendanceRestore' AND \"Quantity\" = 1 AND \"BalanceAfter\" = \"BalanceBefore\" + 1)");
                        });
                });

            modelBuilder.Entity("Academy.Infrastructure.Attendance.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgeCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RecurringScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TrainingGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "AgeCategoryId");

                    b.HasIndex("AcademyId", "BranchId");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "RecurringScheduleId");

                    b.HasIndex("AcademyId", "SportId");

                    b.HasIndex("AcademyId", "SessionDate", "Status");

                    b.HasIndex("AcademyId", "TrainingGroupId", "BranchId", "SportId");

                    b.HasIndex("AcademyId", "TrainingGroupId", "SessionDate", "StartTime")
                        .IsUnique();

                    b.ToTable("TrainingSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrainingSessions_Time", "\"StartTime\" < \"EndTime\"");
                        });
                });

            modelBuilder.Entity("Academy.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Identity.GuardianOtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumberNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumberNormalized", "ExpiresAtUtc");

                    b.ToTable("GuardianOtpChallenges", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Identity.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActiveAcademyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Ticket")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.People.GuardianPlayerLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "PlayerId");

                    b.HasIndex("AcademyId", "GuardianId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GuardianPlayerLinks", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.People.GuardianProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "UserId")
                        .IsUnique();

                    b.ToTable("GuardianProfiles", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.People.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FootballPosition")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoReference")
                        .HasColumnType("text");

                    b.Property<string>("PlayerCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int?>("PreferredFoot")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "ArabicName");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "PlayerCode")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.People.SportEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TrainingGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "BranchId");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "SportId");

                    b.HasIndex("AcademyId", "PlayerId", "SportId", "TrainingGroupId")
                        .IsUnique();

                    b.HasIndex("AcademyId", "TrainingGroupId", "BranchId", "SportId");

                    b.ToTable("SportEnrollments", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.AgeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumBirthYear")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumBirthYear")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "ArabicName")
                        .IsUnique();

                    b.HasIndex("AcademyId", "IsActive");

                    b.ToTable("AgeCategories", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "ArabicName")
                        .IsUnique();

                    b.HasIndex("AcademyId", "IsActive");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.RecurringSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TrainingGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "TrainingGroupId", "DayOfWeek", "StartTime")
                        .IsUnique();

                    b.ToTable("RecurringSchedules", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "ArabicName")
                        .IsUnique();

                    b.HasIndex("AcademyId", "IsActive");

                    b.ToTable("Sports", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.StaffGroupAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TrainingGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "TrainingGroupId");

                    b.ToTable("StaffGroupAssignments", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.TrainingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgeCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "AgeCategoryId");

                    b.HasIndex("AcademyId", "ArabicName")
                        .IsUnique();

                    b.HasIndex("AcademyId", "BranchId");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "SportId");

                    b.ToTable("TrainingGroups", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.BeneficiaryRenewalReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("CodeHint")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SportEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "CodeHash")
                        .IsUnique();

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "SportEnrollmentId", "RevokedAtUtc");

                    b.ToTable("BeneficiaryRenewalReferences", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.PaymentCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RenewalRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "PaymentRequestId")
                        .IsUnique();

                    b.HasIndex("AcademyId", "SportEnrollmentId");

                    b.HasIndex("AcademyId", "RenewalRequestId", "SportEnrollmentId");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.PaymentProviderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingResult")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RawStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "PaymentRequestId");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("PaymentProviderEvents", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.PaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CheckoutReference")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastProviderEventAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ProviderEnvironment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RenewalRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "RenewalRequestId")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderReference")
                        .IsUnique();

                    b.ToTable("PaymentRequests", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PlanNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SportEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SportNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "CollectionId")
                        .IsUnique();

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.RenewalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountExpected")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "RequestedByUserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("AcademyId", "SportEnrollmentId", "SportId");

                    b.HasIndex("AcademyId", "SubscriptionPlanId", "SportId");

                    b.ToTable("RenewalRequests", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.SubscriptionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencySnapshot")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("InitialSessions")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("RemainingSessions")
                        .HasColumnType("integer");

                    b.Property<Guid>("SportEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "CollectionId")
                        .IsUnique();

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "SportEnrollmentId", "SportId");

                    b.HasIndex("AcademyId", "SportEnrollmentId", "StartDate");

                    b.HasIndex("AcademyId", "SubscriptionPlanId", "SportId");

                    b.ToTable("SubscriptionPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionPeriods_RemainingSessions", "\"RemainingSessions\" IS NULL OR \"RemainingSessions\" >= 0");
                        });
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("SessionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("AcademyId", "Id");

                    b.HasIndex("AcademyId", "IsActive");

                    b.HasIndex("AcademyId", "SportId", "ArabicName")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionPlans_Configuration", "(\"PlanType\" = 'Duration' AND \"DurationDays\" > 0 AND \"SessionCount\" IS NULL) OR (\"PlanType\" = 'Sessions' AND \"DurationDays\" IS NULL AND \"SessionCount\" > 0) OR (\"PlanType\" = 'Combined' AND \"DurationDays\" > 0 AND \"SessionCount\" > 0)");
                        });
                });

            modelBuilder.Entity("Academy.Infrastructure.Tenancy.Academy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("EnglishName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Academies", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Tenancy.AcademyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("AcademyMemberships", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Academy.Infrastructure.Attendance.PlayerAttendance", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.SubscriptionPeriod", "ConsumedSubscriptionPeriod")
                        .WithMany()
                        .HasForeignKey("AcademyId", "ConsumedSubscriptionPeriodId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Academy.Infrastructure.People.SportEnrollment", "SportEnrollment")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportEnrollmentId", "TrainingGroupId")
                        .HasPrincipalKey("AcademyId", "Id", "TrainingGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Attendance.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("AcademyId", "TrainingSessionId", "TrainingGroupId")
                        .HasPrincipalKey("AcademyId", "Id", "TrainingGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsumedSubscriptionPeriod");

                    b.Navigation("SportEnrollment");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Academy.Infrastructure.Attendance.StaffAttendance", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Tenancy.AcademyMembership", "AcademyMembership")
                        .WithMany()
                        .HasForeignKey("AcademyId", "AcademyMembershipId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.StaffGroupAssignment", null)
                        .WithMany()
                        .HasForeignKey("AcademyId", "AcademyMembershipId", "TrainingGroupId")
                        .HasPrincipalKey("AcademyId", "AcademyMembershipId", "TrainingGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Attendance.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("AcademyId", "TrainingSessionId", "TrainingGroupId")
                        .HasPrincipalKey("AcademyId", "Id", "TrainingGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademyMembership");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Academy.Infrastructure.Attendance.SubscriptionSessionMovement", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Attendance.PlayerAttendance", "PlayerAttendance")
                        .WithMany()
                        .HasForeignKey("AcademyId", "PlayerAttendanceId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Attendance.SubscriptionSessionMovement", "ReversesMovement")
                        .WithMany()
                        .HasForeignKey("AcademyId", "ReversesMovementId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Academy.Infrastructure.Subscriptions.SubscriptionPeriod", "SubscriptionPeriod")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SubscriptionPeriodId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerAttendance");

                    b.Navigation("ReversesMovement");

                    b.Navigation("SubscriptionPeriod");
                });

            modelBuilder.Entity("Academy.Infrastructure.Attendance.TrainingSession", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.AgeCategory", "AgeCategory")
                        .WithMany()
                        .HasForeignKey("AcademyId", "AgeCategoryId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("AcademyId", "BranchId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.RecurringSchedule", "RecurringSchedule")
                        .WithMany()
                        .HasForeignKey("AcademyId", "RecurringScheduleId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Academy.Infrastructure.Structure.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.TrainingGroup", "TrainingGroup")
                        .WithMany()
                        .HasForeignKey("AcademyId", "TrainingGroupId", "BranchId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id", "BranchId", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeCategory");

                    b.Navigation("Branch");

                    b.Navigation("RecurringSchedule");

                    b.Navigation("Sport");

                    b.Navigation("TrainingGroup");
                });

            modelBuilder.Entity("Academy.Infrastructure.Identity.UserSession", b =>
                {
                    b.HasOne("Academy.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Academy.Infrastructure.People.GuardianPlayerLink", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.People.GuardianProfile", "Guardian")
                        .WithMany()
                        .HasForeignKey("AcademyId", "GuardianId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.People.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AcademyId", "PlayerId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guardian");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Academy.Infrastructure.People.GuardianProfile", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Academy.Infrastructure.People.Player", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Academy.Infrastructure.People.SportEnrollment", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("AcademyId", "BranchId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.People.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AcademyId", "PlayerId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.TrainingGroup", "TrainingGroup")
                        .WithMany()
                        .HasForeignKey("AcademyId", "TrainingGroupId", "BranchId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id", "BranchId", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Player");

                    b.Navigation("Sport");

                    b.Navigation("TrainingGroup");
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.AgeCategory", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.Branch", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.RecurringSchedule", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.TrainingGroup", "TrainingGroup")
                        .WithMany()
                        .HasForeignKey("AcademyId", "TrainingGroupId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingGroup");
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.Sport", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.StaffGroupAssignment", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Tenancy.AcademyMembership", "AcademyMembership")
                        .WithMany()
                        .HasForeignKey("AcademyId", "AcademyMembershipId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.TrainingGroup", "TrainingGroup")
                        .WithMany()
                        .HasForeignKey("AcademyId", "TrainingGroupId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademyMembership");

                    b.Navigation("TrainingGroup");
                });

            modelBuilder.Entity("Academy.Infrastructure.Structure.TrainingGroup", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.AgeCategory", "AgeCategory")
                        .WithMany()
                        .HasForeignKey("AcademyId", "AgeCategoryId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("AcademyId", "BranchId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeCategory");

                    b.Navigation("Branch");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.BeneficiaryRenewalReference", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.People.SportEnrollment", "SportEnrollment")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportEnrollmentId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SportEnrollment");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.PaymentCollection", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.PaymentRequest", "PaymentRequest")
                        .WithMany()
                        .HasForeignKey("AcademyId", "PaymentRequestId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.People.SportEnrollment", "SportEnrollment")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportEnrollmentId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.RenewalRequest", "RenewalRequest")
                        .WithMany()
                        .HasForeignKey("AcademyId", "RenewalRequestId", "SportEnrollmentId")
                        .HasPrincipalKey("AcademyId", "Id", "SportEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentRequest");

                    b.Navigation("RenewalRequest");

                    b.Navigation("SportEnrollment");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.PaymentProviderEvent", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.PaymentRequest", "PaymentRequest")
                        .WithMany()
                        .HasForeignKey("AcademyId", "PaymentRequestId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentRequest");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.PaymentRequest", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.RenewalRequest", "RenewalRequest")
                        .WithMany()
                        .HasForeignKey("AcademyId", "RenewalRequestId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RenewalRequest");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.Receipt", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.PaymentCollection", "Collection")
                        .WithMany()
                        .HasForeignKey("AcademyId", "CollectionId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.RenewalRequest", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.People.SportEnrollment", "SportEnrollment")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportEnrollmentId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SubscriptionPlanId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SportEnrollment");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.SubscriptionPeriod", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.PaymentCollection", "Collection")
                        .WithMany()
                        .HasForeignKey("AcademyId", "CollectionId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.People.SportEnrollment", "SportEnrollment")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportEnrollmentId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Subscriptions.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SubscriptionPlanId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("SportEnrollment");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Academy.Infrastructure.Subscriptions.SubscriptionPlan", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Structure.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("AcademyId", "SportId")
                        .HasPrincipalKey("AcademyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Academy.Infrastructure.Tenancy.AcademyMembership", b =>
                {
                    b.HasOne("Academy.Infrastructure.Tenancy.Academy", "Academy")
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Academy.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Academy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
