import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ContentForm, ContentList } from "./admin-content";

vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn(), replace: vi.fn() }) }));
const ok = (value: unknown) => Promise.resolve(new Response(JSON.stringify(value), { status: 200 }));
beforeEach(() => { global.fetch = vi.fn((input) => String(input).includes("structure/options") ? ok({ sports: [{ id: "f", arabicName: "كرة القدم" }] }) : String(input).includes("people/players") ? ok([{ id: "p", arabicName: "عمر", playerCode: "NG-1" }]) : ok([])); });
afterEach(() => cleanup());

describe("Admin Slice 7 content", () => {
  it("catalog list has required metadata, filters and bounded actions", async () => { global.fetch = vi.fn(() => ok([{ id: "1", arabicName: "كرة تدريب", sport: "كرة القدم", imageReference: "/demo-assets/catalog-football.svg", displayPrice: 450, currency: "EGP", discountPercentage: 10, isActive: true, displayOrder: 1 }])); render(<ContentList kind="catalog" />); expect(await screen.findByText("كرة تدريب")).toBeVisible(); expect(screen.getByText(/450 جنيه · خصم 10% · ترتيب 1/)).toBeVisible(); expect(screen.getAllByText("فعال").some(element => element.matches(".status-badge"))).toBe(true); expect(screen.getByLabelText("فلتر الرياضة")).toBeVisible(); expect(screen.getByLabelText("فلتر حالة المنتج")).toBeVisible(); expect(screen.getByRole("link", { name: "إضافة منتج" })).toBeVisible(); expect(screen.getByRole("link", { name: "عرض" })).toBeVisible(); fireEvent.click(screen.getByLabelText("المزيد من الإجراءات")); expect(screen.getByRole("menuitem", { name: "تعديل" })).toBeVisible(); expect(screen.queryByText(/مخزون|طلبات|مبيعات/)).not.toBeInTheDocument(); });
  it("catalog form has display metadata without commerce workflow", async () => { render(<ContentForm kind="catalog" />); expect(await screen.findByLabelText("الرياضة")).toBeVisible(); expect(screen.getByLabelText("سعر العرض — اختياري")).toBeVisible(); expect(screen.queryByLabelText(/مخزون|شحن|تقييم/)).not.toBeInTheDocument(); });
  it("nutrition form has information and source fields only", async () => { render(<ContentForm kind="nutrition" />); expect(await screen.findByLabelText("وصف الحصة")).toBeVisible(); expect(screen.getByLabelText("حالة البيانات")).toBeVisible(); expect(screen.getByLabelText("وصف المصدر")).toBeVisible(); for (const label of ["السعر", "الخصم", "الكمية", "التقييم", "الطلب"]) expect(screen.queryByLabelText(label, { exact: true })).not.toBeInTheDocument(); });
  it("medical form separates internal and guardian notes", async () => { render(<ContentForm kind="medical" />); expect(await screen.findByLabelText("اللاعب")).toBeVisible(); expect(screen.getByLabelText("ملاحظات داخلية")).toBeVisible(); expect(screen.getByLabelText("ملاحظات ظاهرة لولي الأمر")).toBeVisible(); expect(screen.getByLabelText("منشور لولي الأمر")).toBeVisible(); });
  it("medical list exposes the required filters and localized state", async () => { global.fetch = vi.fn(() => ok([{ id: "1", player: "عمر", type: "Injury", status: "Monitoring", arabicTitle: "إجهاد", recordDate: "2026-09-20", isPublishedToGuardian: true }])); render(<ContentList kind="medical" />); expect(await screen.findByText("إجهاد")).toBeVisible(); expect(screen.getByText(/عمر · إصابة · متابعة · 2026-09-20/)).toBeVisible(); expect(screen.getAllByText("متابعة").some(element => element.matches(".status-badge"))).toBe(true); for (const label of ["فلتر اللاعب", "فلتر نوع السجل", "فلتر الحالة والنشر", "فلتر تاريخ السجل"]) expect(screen.getByLabelText(label)).toBeVisible(); });
  it("gallery form references approved project media and has no fake upload", async () => { render(<ContentForm kind="media" />); expect(await screen.findByLabelText("مرجع وسائط المشروع")).toBeVisible(); expect(screen.queryByText(/رفع ملف|Upload/)).not.toBeInTheDocument(); });
  it("admin lists have useful empty states", async () => { render(<ContentList kind="nutrition" />); await waitFor(() => expect(screen.getByText("لا توجد سجلات مطابقة.")).toBeVisible()); });
});
