"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AdminDataTable, EmptyState, ErrorState, ListSearch, LoadingState, PageHeader, RowActions, StatusBadge } from "../components/dashboard-shell";
import { AttendanceChoice, IdentityMark, ProgressTrack } from "../components/sports-ui";
import { csrfRequest } from "./dashboard-api";

type Session = { id: string; sessionDate: string; startTime: string; endTime: string; status: string; source: string; group: string; sport: string; branch: string; playerCount: number; recorded: number; coaches?: string[] };
type Option = { id: string; arabicName: string };
const sessionLabels: Record<string, string> = { Scheduled: "مجدولة", Held: "تمت", Cancelled: "ملغاة" };
const attendanceLabels: Record<string, string> = { Present: "حاضر", Absent: "غائب", NotRecorded: "لم يُسجل" };
const today = () => new Date().toISOString().slice(0, 10);

export function TrainingSessionsList({ staffOnly = false }: { staffOnly?: boolean }) {
  const [canManage, setCanManage] = useState(false);
  useEffect(() => { fetch("/api/v1/me").then(r => r.ok ? r.json() : null).then(me => setCanManage(me?.role === "AcademyOwner" || me?.role === "AcademyAdmin")).catch(() => undefined); }, []);
  const [sessions, setSessions] = useState<Session[]>([]); const [groups, setGroups] = useState<Option[]>([]); const [search, setSearch] = useState(""); const [fromFilter, setFromFilter] = useState(""); const [toFilter, setToFilter] = useState(""); const [branchFilter, setBranchFilter] = useState(""); const [sportFilter, setSportFilter] = useState(""); const [groupFilter, setGroupFilter] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [showCreate, setShowCreate] = useState(false); const [showGenerate, setShowGenerate] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/v1/attendance/sessions?from=2026-09-21&to=2026-10-05"); if (!response.ok) throw new Error(); setSessions(await response.json() as Session[]); } catch { setError("تعذر تحميل جلسات التدريب."); } finally { setLoading(false); } };
  useEffect(() => { fetch("/api/v1/attendance/sessions").then(async response => { if (!response.ok) throw new Error(); setSessions(await response.json() as Session[]); }).catch(() => setError("تعذر تحميل جلسات التدريب.")).finally(() => setLoading(false)); if (!staffOnly && canManage) fetch("/api/v1/manage/structure/options").then(r => r.ok ? r.json() : null).then((data: { groups?: Option[] } | null) => setGroups(data?.groups ?? [])); }, [staffOnly, canManage]);
  const visible = useMemo(() => sessions.filter(item => `${item.group} ${item.sport} ${item.branch} ${item.sessionDate}`.includes(search) && (!fromFilter || item.sessionDate >= fromFilter) && (!toFilter || item.sessionDate <= toFilter) && (!branchFilter || item.branch === branchFilter) && (!sportFilter || item.sport === sportFilter) && (!groupFilter || item.group === groupFilter) && (!statusFilter || item.status === statusFilter)), [sessions, search, fromFilter, toFilter, branchFilter, sportFilter, groupFilter, statusFilter]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await csrfRequest("/api/v1/attendance/sessions", "POST", { trainingGroupId: form.get("group"), sessionDate: form.get("date"), startTime: `${form.get("start")}:00`, endTime: `${form.get("end")}:00`, notes: form.get("notes") || null }); setShowCreate(false); setMessage("تم إنشاء الحصة."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر الإنشاء."); } }
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const response = await csrfRequest("/api/v1/attendance/sessions/generate", "POST", { from: form.get("from"), to: form.get("to") }); const result = await response.json() as { message: string }; setShowGenerate(false); setMessage(result.message); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر التوليد."); } }
  async function status(id: string, value: "Held" | "Cancelled") { try { await csrfRequest(`/api/v1/attendance/sessions/${id}/status`, "PUT", { status: value }); setMessage(value === "Held" ? "تم إنهاء الحصة." : "تم إلغاء الحصة."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر تغيير الحالة."); } }
  return <><PageHeader title={staffOnly ? "حضور المدربين" : "جلسات التدريب"} context={`الحضور / ${staffOnly ? "حضور المدربين" : "جلسات التدريب"}`} description={staffOnly ? "سجّل حضور الجهاز الفني داخل الجلسات المسندة." : "تابع الجلسات الفعلية واكتمال تسجيل الحضور من مكان واحد."} />{!staffOnly && canManage && <div className="attendance-toolbar"><button className="primary-button" onClick={() => setShowCreate(!showCreate)}>إنشاء حصة</button><button className="secondary-button" onClick={() => setShowGenerate(!showGenerate)}>إنشاء الحصص من الجدول</button></div>}
    {showCreate && <form className="inline-attendance-form" onSubmit={event => void create(event)}><label>المجموعة<select name="group" required><option value="">اختر</option>{groups.map(group => <option key={group.id} value={group.id}>{group.arabicName}</option>)}</select></label><label>التاريخ<input name="date" type="date" defaultValue={today()} required /></label><label>من<input name="start" type="time" defaultValue="18:00" required /></label><label>إلى<input name="end" type="time" defaultValue="19:30" required /></label><label>ملاحظات<input name="notes" /></label><button className="primary-button">حفظ الحصة</button></form>}
    {showGenerate && <form className="inline-attendance-form" onSubmit={event => void generate(event)}><label>من<input name="from" type="date" defaultValue={today()} required /></label><label>إلى<input name="to" type="date" defaultValue="2026-10-04" required /></label><button className="primary-button">إنشاء الحصص</button></form>}
    {message && <p className="success-message" role="status">{message}</p>}{error && <ErrorState message={error} />}<section className="list-card"><div className="session-filters"><ListSearch value={search} onChange={setSearch} label="بحث الجلسات" placeholder="المجموعة، الرياضة، الفرع..." /><label>من<input aria-label="من تاريخ" type="date" value={fromFilter} onChange={event => setFromFilter(event.target.value)} /></label><label>إلى<input aria-label="إلى تاريخ" type="date" value={toFilter} onChange={event => setToFilter(event.target.value)} /></label><select aria-label="فلتر الفرع" value={branchFilter} onChange={event => setBranchFilter(event.target.value)}><option value="">كل الفروع</option>{Array.from(new Set(sessions.map(item => item.branch))).map(value => <option key={value}>{value}</option>)}</select><select aria-label="فلتر الرياضة" value={sportFilter} onChange={event => setSportFilter(event.target.value)}><option value="">كل الرياضات</option>{Array.from(new Set(sessions.map(item => item.sport))).map(value => <option key={value}>{value}</option>)}</select><select aria-label="فلتر المجموعة" value={groupFilter} onChange={event => setGroupFilter(event.target.value)}><option value="">كل المجموعات</option>{Array.from(new Set(sessions.map(item => item.group))).map(value => <option key={value}>{value}</option>)}</select><select aria-label="فلتر حالة الحصة" value={statusFilter} onChange={event => setStatusFilter(event.target.value)}><option value="">كل الحالات</option>{Object.entries(sessionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{loading ? <LoadingState /> : !visible.length ? <EmptyState title="لا توجد جلسات" message="لا توجد حصص في النطاق أو الفلاتر الحالية." /> : <AdminDataTable label="جلسات التدريب" rows={visible} rowKey={item => item.id} columns={[
      { key: "date", header: "التاريخ والوقت", primary: true, width: "minmax(8rem, 1.1fr)", render: item => <span className="session-date"><strong>{item.sessionDate}</strong><small>{item.startTime.slice(0, 5)}–{item.endTime.slice(0, 5)}</small></span> },
      { key: "group", header: "المجموعة والمدرب", width: "minmax(9rem, 1.6fr)", render: item => <>{item.group}<small>{item.coaches?.join("، ") || "لا يوجد إسناد فعال"}</small></> },
      { key: "sport", header: "الرياضة والفرع", width: "minmax(8rem, 1.3fr)", render: item => <>{item.sport}<small>{item.branch}</small></> },
      { key: "completion", header: "اكتمال الحضور", width: "minmax(6rem, .8fr)", render: item => <span className="session-completion">{item.recorded}/{item.playerCount} مسجل<ProgressTrack value={item.recorded} total={item.playerCount} label={`اكتمال حضور ${item.group}`} /></span> },
      { key: "status", header: "الحالة", width: "minmax(5rem, .7fr)", render: item => <StatusBadge status={item.status} /> },
      { key: "actions", header: "الإجراءات", width: "minmax(8rem, .9fr)", render: item => <RowActions actions={item.status === "Cancelled" ? [] : [{ label: staffOnly ? "حضور المدربين" : "تسجيل الحضور", href: staffOnly ? `/dashboard/attendance/sessions/${item.id}/staff` : `/dashboard/attendance/sessions/${item.id}/players` }, ...(!staffOnly && canManage && item.status === "Scheduled" ? [{ label: "إنهاء الحصة", onClick: () => void status(item.id, "Held") }, { label: "إلغاء", tone: "danger" as const, onClick: () => void status(item.id, "Cancelled") }] : [])]} /> },
    ]} />}</section></>;
}

type Roster = { session: { id: string; sessionDate: string; startTime: string; endTime: string; status: string; group: string; sport: string; branch: string }; players: PlayerRow[] };
type PlayerRow = { sportEnrollmentId: string; playerCode: string; arabicName: string; photoReference?: string; attendanceStatus: string; subscriptionPlan?: string; subscriptionType?: string; remainingSessions?: number; sessionConsumed: boolean; warning?: string };
export function PlayerAttendance({ sessionId }: { sessionId: string }) {
  const [data, setData] = useState<Roster | null>(null); const [states, setStates] = useState<Record<string, string>>({}); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { const response = await fetch(`/api/v1/attendance/sessions/${sessionId}/players`); if (!response.ok) return setError("تعذر تحميل كشف اللاعبين."); const roster = await response.json() as Roster; setData(roster); setStates(Object.fromEntries(roster.players.map(row => [row.sportEnrollmentId, row.attendanceStatus]))); };
  useEffect(() => { fetch(`/api/v1/attendance/sessions/${sessionId}/players`).then(async response => { if (!response.ok) throw new Error(); const roster = await response.json() as Roster; setData(roster); setStates(Object.fromEntries(roster.players.map(row => [row.sportEnrollmentId, row.attendanceStatus]))); }).catch(() => setError("تعذر تحميل كشف اللاعبين.")); }, [sessionId]);
  const visible = data?.players.filter(row => `${row.playerCode} ${row.arabicName}`.includes(search)) ?? [];
  async function save() { if (!data) return; setSaving(true); setError(""); setMessage(""); try { const items = data.players.map(row => ({ sportEnrollmentId: row.sportEnrollmentId, status: states[row.sportEnrollmentId] === "Present" ? 2 : states[row.sportEnrollmentId] === "Absent" ? 3 : 1 })); const response = await csrfRequest(`/api/v1/attendance/sessions/${sessionId}/players`, "PUT", { items }); const result = await response.json() as { items: { warning?: string }[] }; setMessage(result.items.some(item => item.warning) ? `تم الحفظ. ${result.items.find(item => item.warning)?.warning}` : "تم حفظ الحضور بنجاح."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر الحفظ."); } finally { setSaving(false); } }
  if (!data && !error) return <LoadingState />;
  return <><PageHeader title="حضور اللاعبين" context="الحضور / جلسات التدريب" />{error && <ErrorState message={error} />}{data && <><section className="session-summary"><strong>{data.session.sessionDate} · {data.session.startTime.slice(0, 5)}–{data.session.endTime.slice(0, 5)}</strong><span>{data.session.group} · {data.session.sport} · {data.session.branch}</span></section><section className="list-card"><div className="attendance-actions"><ListSearch value={search} onChange={setSearch} label="بحث بالاسم أو كود اللاعب" placeholder="اسم اللاعب أو الكود" /><button className="secondary-button" type="button" onClick={() => setStates(Object.fromEntries(data.players.map(row => [row.sportEnrollmentId, "Present"]))) }>تحديد الحاضرين</button></div><div className="attendance-roster">{visible.map(row => <article key={row.sportEnrollmentId}><div className="player-identity"><div><IdentityMark name={row.arabicName} /><small>{row.playerCode} · {row.subscriptionPlan ?? "لا يوجد اشتراك مؤهل"}{row.remainingSessions != null ? ` · الرصيد: ${row.remainingSessions}` : ""}</small>{row.warning && <em>{row.warning}</em>}</div></div><div className="status-picker" role="group" aria-label={`حضور ${row.arabicName}`}>{["Present", "Absent", "NotRecorded"].map(value => <AttendanceChoice value={value} selected={states[row.sportEnrollmentId] === value} onClick={() => setStates({ ...states, [row.sportEnrollmentId]: value })} key={value} />)}</div></article>)}</div>{message && <p className="success-message" role="status">{message}</p>}<button className="primary-button attendance-save" disabled={saving || data.session.status === "Cancelled"} onClick={() => void save()}>{saving ? "جارٍ الحفظ…" : "حفظ الحضور"}</button></section></>}</>;
}

type StaffRow = { academyMembershipId: string; name: string; role: string; attendanceStatus: string };
export function StaffAttendance({ sessionId }: { sessionId: string }) { const [rows, setRows] = useState<StaffRow[]>([]); const [states, setStates] = useState<Record<string, string>>({}); const [message, setMessage] = useState(""); const [error, setError] = useState(""); useEffect(() => { fetch(`/api/v1/attendance/sessions/${sessionId}/staff`).then(async response => { if (!response.ok) throw new Error(); const result = await response.json() as StaffRow[]; setRows(result); setStates(Object.fromEntries(result.map(row => [row.academyMembershipId, row.attendanceStatus]))); }).catch(() => setError("تعذر تحميل حضور الجهاز الفني.")); }, [sessionId]); async function save() { try { await csrfRequest(`/api/v1/attendance/sessions/${sessionId}/staff`, "PUT", { items: rows.map(row => ({ academyMembershipId: row.academyMembershipId, status: states[row.academyMembershipId] === "Present" ? 2 : states[row.academyMembershipId] === "Absent" ? 3 : 1 })) }); setMessage("تم حفظ حضور الجهاز الفني."); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر الحفظ."); } } return <><PageHeader title="حضور المدربين" context="الحضور / حضور المدربين" />{error && <ErrorState message={error} />}<section className="list-card">{!rows.length ? <EmptyState message="لا يوجد جهاز فني مكلف بهذه المجموعة." /> : <div className="attendance-roster">{rows.map(row => <article key={row.academyMembershipId}><div><strong>{row.name}</strong><small>{row.role}</small></div><div className="status-picker" role="group" aria-label={`حضور ${row.name}`}>{["Present", "Absent", "NotRecorded"].map(value => <AttendanceChoice value={value} selected={states[row.academyMembershipId] === value} onClick={() => setStates({ ...states, [row.academyMembershipId]: value })} key={value} />)}</div></article>)}</div>}{message && <p className="success-message">{message}</p>}{rows.length > 0 && <button className="primary-button attendance-save" onClick={() => void save()}>حفظ حضور المدربين</button>}</section></>; }

type HistoryRow = { id: string; playerCode: string; player: string; group: string; sport: string; branch: string; sessionDate: string; startTime: string; status: string; sessionConsumed: boolean };
export function AttendanceHistory() { const [rows, setRows] = useState<HistoryRow[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState(""); useEffect(() => { const query = new URLSearchParams(); if (search) query.set("search", search); if (status) query.set("status", status); const timer = setTimeout(() => fetch(`/api/v1/attendance/history?${query}`).then(async response => { if (!response.ok) throw new Error(); setRows(await response.json() as HistoryRow[]); }).catch(() => setError("تعذر تحميل سجل الحضور.")), 200); return () => clearTimeout(timer); }, [search, status]); return <><PageHeader title="سجل الحضور" context="الحضور / سجل الحضور" description="راجع الحالات المسجلة فعليًا لكل لاعب وجلسة تدريب." />{error && <ErrorState message={error} />}<section className="list-card"><div className="player-filters"><ListSearch value={search} onChange={setSearch} label="بحث سجل الحضور" placeholder="الاسم أو كود اللاعب" /><select aria-label="حالة الحضور" value={status} onChange={event => setStatus(event.target.value)}><option value="">كل الحالات</option><option value="Present">حاضر</option><option value="Absent">غائب</option><option value="NotRecorded">لم يُسجل</option></select></div>{!rows.length ? <EmptyState title="لا توجد سجلات حضور" message="لا توجد سجلات مطابقة للبحث والحالة المختارة." /> : <AdminDataTable label="سجل الحضور" rows={rows} rowKey={row => row.id} columns={[
    { key: "player", header: "اللاعب", primary: true, width: "minmax(12rem, 1.5fr)", render: row => <><strong>{row.player}</strong><small dir="ltr">{row.playerCode}</small></> },
    { key: "session", header: "التاريخ والوقت", width: "minmax(8rem, 1fr)", render: row => <>{row.sessionDate}<small>{row.startTime.slice(0, 5)}</small></> },
    { key: "group", header: "المجموعة", width: "minmax(11rem, 1.35fr)", render: row => row.group },
    { key: "location", header: "الرياضة والفرع", width: "minmax(10rem, 1.2fr)", render: row => <>{row.sport}<small>{row.branch}</small></> },
    { key: "status", header: "الحالة", width: "minmax(7rem, .7fr)", render: row => <><StatusBadge status={row.status} />{row.sessionConsumed && <small>تم خصم حصة</small>}</> },
  ]} />}</section></>; }

export function GuardianAttendanceList({ playerId }: { playerId: string }) { const [rows, setRows] = useState<{ id: string; sessionDate: string; startTime: string; group: string; sport: string; status: string }[]>([]); useEffect(() => { fetch(`/api/v1/guardian/children/${playerId}/attendance`).then(response => response.ok ? response.json() : []).then(setRows); }, [playerId]); return <section className="guardian-attendance"><h3>آخر الحضور</h3>{rows.length === 0 ? <small>لا يوجد حضور مسجل بعد.</small> : rows.slice(0, 5).map(row => <p key={row.id}><span>{row.sessionDate} · {row.sport} · {row.group}</span><b>{attendanceLabels[row.status]}</b></p>)}</section>; }
