"use client";

import Link from "next/link";
import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ConfirmationDialog, EmptyState, ErrorState, ListSearch, LoadingState, PageHeader, RowActions } from "../components/dashboard-shell";
import { csrfRequest } from "./dashboard-api";

const axisLabels: Record<string, string> = { Passing: "التمرير", Dribbling: "المراوغة", Speed: "السرعة", Defending: "الدفاع", Physical: "القوة البدنية", Shooting: "التسديد" };
const statusLabels: Record<string, string> = { Draft: "مسودة", Published: "منشور", Superseded: "مستبدل" };
const footLabels: Record<string, string> = { Right: "اليمنى", Left: "اليسرى", Both: "القدمان" };

type Criterion = { id: string; sportId: string; sport: string; arabicName: string; englishName?: string; description?: string; displayOrder: number; isActive: boolean; weight: number; footballAxis?: string; version: number; referenced: boolean };
type EnrollmentOption = { id: string; playerId: string; player: string; playerCode: string; sportId: string; sport: string; groupId: string; group: string };
type OptionData = { enrollments: EnrollmentOption[]; sports: { id: string; name: string }[] };

export function CriteriaList() {
  const [rows, setRows] = useState<Criterion[]>([]); const [search, setSearch] = useState(""); const [sport, setSport] = useState(""); const [active, setActive] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { const query = new URLSearchParams(); if (sport) query.set("sportId", sport); if (active) query.set("active", active); fetch(`/api/v1/evaluations/criteria?${query}`).then(async response => { if (!response.ok) throw new Error(); setRows(await response.json() as Criterion[]); }).catch(() => setError("تعذر تحميل معايير التقييم.")).finally(() => setLoading(false)); }, [sport, active]);
  const sports = Array.from(new Map(rows.map(x => [x.sportId, x.sport])).entries()); const visible = rows.filter(x => !search || x.arabicName.includes(search));
  async function toggle(row: Criterion) { try { const response = await csrfRequest(`/api/v1/evaluations/criteria/${row.id}/status`, "PUT", { isActive: !row.isActive, version: row.version }); const updated = await response.json() as { version: number }; setRows(items => items.map(x => x.id === row.id ? { ...x, isActive: !x.isActive, version: updated.version } : x)); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر تغيير الحالة."); } }
  return <><PageHeader title="معايير التقييم" context="التقييمات / معايير التقييم" action={{ label: "إضافة معيار", href: "/dashboard/evaluations/criteria/new" }} />{error && <ErrorState message={error} />}<section className="list-card"><div className="player-filters"><ListSearch value={search} onChange={setSearch} placeholder="ابحث باسم المعيار" /><select aria-label="الرياضة" value={sport} onChange={e => setSport(e.target.value)}><option value="">كل الرياضات</option>{sports.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select aria-label="الحالة" value={active} onChange={e => setActive(e.target.value)}><option value="">كل الحالات</option><option value="true">فعال</option><option value="false">متوقف</option></select></div>{loading ? <LoadingState /> : visible.length === 0 ? <EmptyState message="لا توجد معايير مطابقة." /> : <div className="data-list">{visible.map(row => <article className={!row.isActive ? "inactive-record" : ""} key={row.id}><div><strong>{row.arabicName}</strong><small>{row.sport} · {row.footballAxis ? axisLabels[row.footballAxis] : "بدون محور كرة قدم"} · الوزن {row.weight} · الترتيب {row.displayOrder} · {row.isActive ? "فعال" : "متوقف"}</small></div><RowActions actions={[{ label: "تعديل", href: `/dashboard/evaluations/criteria/${row.id}/edit` }, { label: row.isActive ? "إيقاف" : "تفعيل", onClick: () => void toggle(row) }]} /></article>)}</div>}</section></>;
}

export function CriterionForm({ id }: { id?: string }) {
  const router = useRouter(); const [options, setOptions] = useState<OptionData>({ enrollments: [], sports: [] }); const [current, setCurrent] = useState<Criterion | null>(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/v1/evaluations/options").then(r => r.json()), id ? fetch("/api/v1/evaluations/criteria").then(r => r.json()) : Promise.resolve([])]).then(([o, rows]) => { setOptions(o as OptionData); if (id) setCurrent((rows as Criterion[]).find(x => x.id === id) ?? null); }).catch(() => setError("تعذر تحميل بيانات النموذج.")); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const body = { sportId: data.get("sportId"), arabicName: data.get("arabicName"), englishName: data.get("englishName"), description: data.get("description"), footballAxis: data.get("footballAxis") || null, weight: Number(data.get("weight")), displayOrder: Number(data.get("displayOrder")), isActive: data.get("isActive") === "on", version: current?.version ?? 0 }; try { await csrfRequest(id ? `/api/v1/evaluations/criteria/${id}` : "/api/v1/evaluations/criteria", id ? "PUT" : "POST", body); router.push("/dashboard/evaluations/criteria"); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر حفظ المعيار."); } }
  if (id && !current && !error) return <LoadingState />;
  return <><PageHeader title={id ? "تعديل معيار" : "إضافة معيار"} context="التقييمات / معايير التقييم" /><form className="form-shell" onSubmit={event => void submit(event)}><label>الرياضة<select name="sportId" defaultValue={current?.sportId} required><option value="">اختر الرياضة</option>{options.sports.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الاسم بالعربية<input name="arabicName" defaultValue={current?.arabicName} required /></label><label>الاسم بالإنجليزية — اختياري<input name="englishName" dir="ltr" defaultValue={current?.englishName} /></label><label>الوصف — اختياري<textarea name="description" defaultValue={current?.description} /></label><label>المحور — لكرة القدم فقط<select name="footballAxis" defaultValue={current?.footballAxis ?? ""}><option value="">بدون محور</option>{Object.entries(axisLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>الوزن<input name="weight" type="number" min="0.001" step="0.001" defaultValue={current?.weight ?? 1} required /></label><label>الترتيب<input name="displayOrder" type="number" min="0" defaultValue={current?.displayOrder ?? 0} required /></label><label className="check-field"><input name="isActive" type="checkbox" defaultChecked={current?.isActive ?? true} /> فعال</label>{error && <ErrorState message={error} />}<div className="form-actions"><button className="primary-button">حفظ المعيار</button><button type="button" onClick={() => router.back()}>إلغاء</button></div></form></>;
}

type EvaluationRow = { id: string; player: string; sport: string; group: string; evaluationDate: string; evaluator: string; status: string; overallScore?: number; scoredCriteria: number; totalApplicableCriteria: number; completenessPercentage: number; version: number };
export function EvaluationsList({ publishedOnly = false }: { publishedOnly?: boolean }) {
  const [rows, setRows] = useState<EvaluationRow[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(publishedOnly ? "Published" : ""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { const query = new URLSearchParams(); if (search) query.set("search", search); if (status) query.set("status", status); const timer = setTimeout(() => fetch(`/api/v1/evaluations?${query}`).then(async r => { if (!r.ok) throw new Error(); setRows(await r.json() as EvaluationRow[]); }).catch(() => setError("تعذر تحميل التقييمات.")).finally(() => setLoading(false)), 150); return () => clearTimeout(timer); }, [search, status]);
  return <><PageHeader title={publishedOnly ? "التقارير المنشورة" : "تقييمات اللاعبين"} context={`التقييمات / ${publishedOnly ? "التقارير المنشورة" : "تقييمات اللاعبين"}`} action={!publishedOnly ? { label: "تقييم جديد", href: "/dashboard/evaluations/new" } : undefined} />{error && <ErrorState message={error} />}<section className="list-card"><div className="player-filters"><ListSearch value={search} onChange={setSearch} placeholder="اسم اللاعب أو الكود" />{!publishedOnly && <select aria-label="حالة التقييم" value={status} onChange={e => setStatus(e.target.value)}><option value="">كل الحالات</option><option value="Draft">مسودة</option><option value="Published">منشور</option></select>}</div>{loading ? <LoadingState /> : rows.length === 0 ? <EmptyState message="لا توجد تقييمات مطابقة." /> : <div className="data-list">{rows.map(row => <article key={row.id}><div><strong>{row.player} — {row.sport}</strong><small>{row.group} · {row.evaluationDate} · {row.evaluator} · {statusLabels[row.status]} · الاكتمال {row.scoredCriteria}/{row.totalApplicableCriteria}{row.overallScore != null ? ` · الإجمالي ${row.overallScore}` : ""}</small></div><RowActions actions={row.status === "Draft" ? [{ label: "عرض وتعديل", href: `/dashboard/evaluations/${row.id}/edit` }] : [{ label: "عرض التقرير", href: `/dashboard/evaluations/${row.id}/report` }]} /></article>)}</div>}</section></>;
}

export function NewEvaluation() {
  const router = useRouter(); const [options, setOptions] = useState<OptionData>({ enrollments: [], sports: [] }); const [sport, setSport] = useState(""); const [group, setGroup] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/v1/evaluations/options").then(r => r.json()).then(setOptions).catch(() => setError("تعذر تحميل اللاعبين المتاحين.")); }, []);
  const visible = options.enrollments.filter(x => (!sport || x.sportId === sport) && (!group || x.groupId === group)); const sports = Array.from(new Map(options.enrollments.map(x => [x.sportId, x.sport])).entries()); const groups = Array.from(new Map(options.enrollments.filter(x => !sport || x.sportId === sport).map(x => [x.groupId, x.group])).entries());
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const response = await csrfRequest("/api/v1/evaluations", "POST", { sportEnrollmentId: data.get("enrollmentId"), evaluationDate: data.get("evaluationDate"), reportingPeriod: data.get("reportingPeriod"), generalNotes: data.get("generalNotes") }); const created = await response.json() as { id: string }; router.push(`/dashboard/evaluations/${created.id}/edit`); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر إنشاء التقييم."); } }
  return <><PageHeader title="تقييم جديد" context="التقييمات / تقييمات اللاعبين" /><form className="form-shell" onSubmit={event => void submit(event)}><label>الرياضة<select aria-label="الرياضة" value={sport} onChange={e => { setSport(e.target.value); setGroup(""); }}><option value="">كل الرياضات</option>{sports.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>المجموعة<select aria-label="المجموعة" value={group} onChange={e => setGroup(e.target.value)}><option value="">كل المجموعات</option>{groups.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>اللاعب<select name="enrollmentId" required><option value="">اختر اللاعب</option>{visible.map(x => <option key={x.id} value={x.id}>{x.player} — {x.sport} — {x.group}</option>)}</select></label><label>تاريخ التقييم<input name="evaluationDate" type="date" defaultValue="2026-09-28" required /></label><label>فترة التقرير<input name="reportingPeriod" defaultValue="سبتمبر 2026" required /></label><label>ملاحظات عامة<textarea name="generalNotes" /></label>{error && <ErrorState message={error} />}<div className="form-actions"><button className="primary-button">إنشاء المسودة</button><button type="button" onClick={() => router.back()}>إلغاء</button></div></form></>;
}

type EvaluationDetails = { id: string; player: string; sport: string; group: string; evaluationDate: string; reportingPeriod: string; status: string; generalNotes?: string; version: number; scores: { criterionId: string; name: string; score?: number; notes?: string; axis?: string }[] };
export function EvaluationEditor({ id }: { id: string }) {
  const router = useRouter(); const [data, setData] = useState<EvaluationDetails | null>(null); const [scores, setScores] = useState<Record<string, string>>({}); const [notes, setNotes] = useState<Record<string, string>>({}); const [general, setGeneral] = useState(""); const [error, setError] = useState(""); const [dialog, setDialog] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/v1/evaluations/${id}`).then(async response => { if (!response.ok) throw new Error(); const item = await response.json() as EvaluationDetails; setData(item); setGeneral(item.generalNotes ?? ""); setScores(Object.fromEntries(item.scores.map(x => [x.criterionId, x.score == null ? "" : String(x.score)]))); setNotes(Object.fromEntries(item.scores.map(x => [x.criterionId, x.notes ?? ""]))); }).catch(() => setError("تعذر تحميل التقييم أو أنه خارج نطاقك.")); }, [id]);
  async function save() { if (!data) return false; setBusy(true); setError(""); try { const response = await csrfRequest(`/api/v1/evaluations/${id}`, "PUT", { reportingPeriod: data.reportingPeriod, generalNotes: general, version: data.version, scores: data.scores.map(x => ({ criterionId: x.criterionId, score: scores[x.criterionId] === "" ? null : Number(scores[x.criterionId]), notes: notes[x.criterionId] })) }); const result = await response.json() as { version: number }; setData({ ...data, version: result.version }); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر حفظ المسودة."); return false; } finally { setBusy(false); } }
  async function publish() { if (!data) return; const saved = await save(); if (!saved) return; const refreshed = await fetch(`/api/v1/evaluations/${id}`).then(r => r.json()) as EvaluationDetails; try { await csrfRequest(`/api/v1/evaluations/${id}/publish`, "POST", { version: refreshed.version }); router.push(`/dashboard/evaluations/${id}/report`); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر نشر التقييم."); setDialog(false); } }
  if (!data) return <><PageHeader title="تقييم اللاعب" context="التقييمات / تعديل" />{error ? <ErrorState message={error} /> : <LoadingState />}</>;
  return <><PageHeader title={`تقييم ${data.player}`} context={`${data.sport} / ${data.group}`} />{error && <ErrorState message={error} />}<section className="evaluation-editor"><div className="report-meta"><b>{data.evaluationDate}</b><span>{data.reportingPeriod}</span><span>مسودة خاصة بفريق العمل</span></div><label className="field">ملاحظات عامة<textarea value={general} onChange={e => setGeneral(e.target.value)} /></label><div className="score-grid">{data.scores.map(item => <article className="score-card" key={item.criterionId}><h3>{item.name}</h3>{item.axis && <small>{axisLabels[item.axis]}</small>}<label>الدرجة من 100<input aria-label={`درجة ${item.name}`} inputMode="numeric" type="number" min="0" max="100" value={scores[item.criterionId] ?? ""} onChange={e => setScores({ ...scores, [item.criterionId]: e.target.value })} /></label><label>ملاحظة — اختياري<textarea aria-label={`ملاحظة ${item.name}`} value={notes[item.criterionId] ?? ""} onChange={e => setNotes({ ...notes, [item.criterionId]: e.target.value })} /></label></article>)}</div><div className="form-actions sticky-actions"><button className="secondary-button" disabled={busy} onClick={() => void save()}>{busy ? "جارٍ الحفظ…" : "حفظ المسودة"}</button><button className="primary-button" disabled={busy} onClick={() => setDialog(true)}>نشر التقييم</button></div></section><ConfirmationDialog open={dialog} title="نشر التقييم" message="سيظهر التقييم المنشور لولي الأمر ولن يمكن تعديله مباشرةً." confirmLabel="تأكيد النشر" busy={busy} onConfirm={() => void publish()} onCancel={() => setDialog(false)} /></>;
}

type Report = { id: string; player: string; photoReference?: string; footballPosition?: string; sport: string; evaluationDate: string; reportingPeriod: string; evaluator: string; generalNotes?: string; age: number; heightCm?: number; weightKg?: number; preferredFoot?: string; isFootballReport: boolean; overallScore?: number; scoredCriteria: number; totalApplicableCriteria: number; completenessPercentage: number; availableAxes: number; axes: { axis: string; value?: number }[]; criteria: { name: string; score?: number; notes?: string; axis?: string }[] };
export function EvaluationReport({ id, guardian = false }: { id: string; guardian?: boolean }) { const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(""); useEffect(() => { fetch(guardian ? `/api/v1/guardian/evaluations/${id}/report` : `/api/v1/evaluations/${id}/report`).then(async r => { if (!r.ok) throw new Error(); setReport(await r.json() as Report); }).catch(() => setError("تعذر تحميل التقرير أو أنه غير متاح لك.")); }, [id, guardian]); if (error) return <ErrorState message={error} />; if (!report) return <LoadingState />; return <main className={guardian ? "page-shell guardian-report-shell" : ""}><PageHeader title="تقرير اللاعب" context={`${report.player} / ${report.sport}`} /><section className="player-report"><header className="report-hero">{report.photoReference ? <Image className="player-avatar" src={report.photoReference} alt={`صورة ${report.player}`} width={64} height={64} /> : <div className="player-avatar" aria-hidden="true">{report.player.slice(0, 1)}</div>}<div><h2>{report.player}</h2><p>{report.footballPosition ?? report.sport} · {report.evaluationDate} · {report.evaluator}</p></div><div className="overall-score"><b>{report.overallScore ?? "—"}</b><span>التقييم الإجمالي</span></div></header>{report.isFootballReport ? <><RadarChart axes={report.axes} /><div className="axis-values" aria-label="القيم النصية للمحاور">{report.axes.map(x => <div key={x.axis}><span>{axisLabels[x.axis]}</span><b>{x.value ?? "غير متاح"}</b></div>)}</div></> : <p className="neutral-summary">الملخص الرسومي لهذه الرياضة غير مُعرّف بعد.</p>}<div className="info-cards"><article><span>العمر</span><b>{report.age} سنوات</b></article><article><span>الطول</span><b>{report.heightCm ? `${report.heightCm} سم` : "غير مسجل"}</b></article><article><span>الوزن</span><b>{report.weightKg ? `${report.weightKg} كجم` : "غير مسجل"}</b></article><article><span>القدم المفضلة</span><b>{report.preferredFoot ? footLabels[report.preferredFoot] : "غير منطبق/مسجل"}</b></article></div><div className="completeness"><b>اكتمال التقييم: {report.scoredCriteria}/{report.totalApplicableCriteria} ({report.completenessPercentage}%)</b>{report.isFootballReport && <span>المحاور المتاحة: {report.availableAxes}/6</span>}</div><section><h2>المعايير التفصيلية</h2><div className="score-grid">{report.criteria.map(item => <article className="score-card" key={item.name}><h3>{item.name}</h3>{item.axis && <small>{axisLabels[item.axis]}</small>}<strong>{item.score == null ? "لم يُقيّم" : `${item.score} / 100`}</strong>{item.notes && <p>{item.notes}</p>}</article>)}</div></section>{report.generalNotes && <section className="coach-notes"><h2>ملاحظات المدرب</h2><p>{report.generalNotes}</p></section>}</section></main>; }

function RadarChart({ axes }: { axes: { axis: string; value?: number }[] }) { const points = axes.map((x, i) => { const value = x.value ?? 0; const angle = -Math.PI / 2 + i * Math.PI / 3; const radius = 82 * value / 100; return `${100 + Math.cos(angle) * radius},${100 + Math.sin(angle) * radius}`; }).join(" "); const rings = [25, 50, 75, 100].map(level => axes.map((_, i) => { const angle = -Math.PI / 2 + i * Math.PI / 3; const radius = 82 * level / 100; return `${100 + Math.cos(angle) * radius},${100 + Math.sin(angle) * radius}`; }).join(" ")); return <figure className="radar"><svg viewBox="0 0 200 200" role="img" aria-label="مخطط محاور أداء كرة القدم"><title>المخطط السداسي لأداء اللاعب</title>{rings.map((ring, i) => <polygon key={i} points={ring} className="radar-ring" />)}{axes.map((_, i) => { const angle = -Math.PI / 2 + i * Math.PI / 3; return <line key={i} x1="100" y1="100" x2={100 + Math.cos(angle) * 82} y2={100 + Math.sin(angle) * 82} className="radar-line" />; })}<polygon points={points} className="radar-value" /></svg><figcaption>القيم الناقصة لا تدخل الحساب وتظهر نصيًا كغير متاحة.</figcaption></figure>; }

export function GuardianEvaluationHistory({ playerId }: { playerId: string }) { const [rows, setRows] = useState<{ id: string; sport: string; evaluationDate: string; evaluator: string; overallScore?: number; completenessPercentage: number }[]>([]); useEffect(() => { fetch(`/api/v1/guardian/children/${playerId}/evaluations`).then(r => r.ok ? r.json() : []).then(setRows); }, [playerId]); return <section className="guardian-evaluations"><h3>تقرير اللاعب</h3>{rows.length === 0 ? <small>لا توجد تقييمات منشورة بعد.</small> : rows.map(row => <p key={row.id}><span>{row.sport} · {row.evaluationDate} · {row.evaluator}</span><Link href={`/guardian/evaluations/${row.id}`}>عرض التقرير{row.overallScore != null ? ` · ${row.overallScore}` : ""}</Link></p>)}</section>; }
