"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "../components/dashboard-shell";
import { GuardianShell } from "../components/guardian-shell";

type CatalogSection = { sportId: string; sport: string; items: { id: string; arabicName: string; arabicDescription?: string; imageReference: string; displayPrice?: number; currency?: string; discountPercentage?: number }[] };
const categoryLabels = { Breakfast: "الإفطار", Lunch: "الغداء", Dinner: "العشاء" } as const;
const typeLabels: Record<string, string> = { Injury: "إصابة", Consultation: "استشارة", Image: "صورة", Video: "فيديو" };
const medicalStatus: Record<string, string> = { Open: "مفتوح", Monitoring: "متابعة", Resolved: "مغلق" };

export function GuardianSportCatalog() {
  const [sections, setSections] = useState<CatalogSection[] | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/v1/guardian/catalog").then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(value => setSections(Array.isArray(value) ? value : [])).catch(() => setError("تعذر تحميل المنتجات الرياضية.")); }, []);
  return <section className="guardian-section catalog-section" aria-labelledby="catalog-heading"><div className="guardian-section-title"><h2 id="catalog-heading">المنتجات الرياضية</h2><span>كتالوج للعرض فقط</span></div>{error && <ErrorState message={error} />}{!sections && !error ? <LoadingState /> : sections?.length === 0 ? <EmptyState message="لا توجد منتجات منشورة لرياضات الأبناء." /> : sections?.map(section => <div className="catalog-sport" key={section.sportId}><h3>{section.sport}</h3><div className="catalog-grid">{section.items.map(item => <article key={item.id}><Image src={item.imageReference} alt="" width={640} height={420} /><div><h4>{item.arabicName}</h4>{item.arabicDescription && <p>{item.arabicDescription}</p>}{item.displayPrice != null && <span className="display-price">{item.displayPrice} {item.currency === "EGP" ? "جنيه" : item.currency}</span>}{item.discountPercentage != null && item.discountPercentage > 0 && <small>خصم عرضي {item.discountPercentage}%</small>}</div></article>)}</div></div>)}</section>;
}

type NutritionCard = { id: string; arabicName: string; arabicDescription: string; imageReference: string; category: keyof typeof categoryLabels; dataStatus: string };
export function NutritionLibrary({ playerId }: { playerId: string }) {
  const [category, setCategory] = useState<keyof typeof categoryLabels>("Breakfast"); const [items, setItems] = useState<NutritionCard[] | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/v1/guardian/nutrition?category=${category}`).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(setItems).catch(() => setError("تعذر تحميل مكتبة التغذية.")); }, [category]);
  return <GuardianShell><Link className="back-link" href={`/guardian/children/${playerId}`}>العودة لملف الطفل</Link><header className="guardian-page-header"><span>مكتبة معلومات عامة</span><h1>التغذية والصحة</h1><p>معلومات غير شخصية ولا تمثل وصفة أو خطة علاجية.</p></header><div className="nutrition-tabs" role="tablist" aria-label="أقسام التغذية">{Object.entries(categoryLabels).map(([value, label]) => <button role="tab" aria-selected={category === value} className={category === value ? "active" : ""} key={value} onClick={() => setCategory(value as keyof typeof categoryLabels)}>{label}</button>)}</div>{error && <ErrorState message={error} />}{!items && !error ? <LoadingState /> : items?.length === 0 ? <EmptyState message="لا توجد مواد منشورة في هذا القسم." /> : <div className="nutrition-grid">{items?.map(item => <Link href={`/guardian/nutrition/${item.id}?player=${playerId}`} key={item.id}><Image src={item.imageReference} alt="" width={640} height={420} /><h2>{item.arabicName}</h2><p>{item.arabicDescription}</p>{item.dataStatus === "DemoUnreviewed" && <small>بيانات تجريبية غير مراجعة</small>}</Link>)}</div>}</GuardianShell>;
}

type NutritionDetailsData = { id: string; arabicName: string; arabicDescription: string; imageReference: string; servingDescription: string; calories?: number; proteinGrams?: number; carbohydratesGrams?: number; fatGrams?: number; dataStatus: string; sourceDescription?: string };
export function NutritionDetails({ id, playerId }: { id: string; playerId?: string }) {
  const [item, setItem] = useState<NutritionDetailsData | null>(null); const [error, setError] = useState(""); useEffect(() => { fetch(`/api/v1/guardian/nutrition/${id}`).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(setItem).catch(() => setError("تعذر تحميل تفاصيل الوجبة.")); }, [id]);
  return <GuardianShell>{error && <ErrorState message={error} />}{!item && !error ? <LoadingState /> : item && <><Link className="back-link" href={playerId ? `/guardian/children/${playerId}/nutrition` : "/guardian"}>العودة للمكتبة</Link><article className="meal-details"><Image src={item.imageReference} alt="" width={640} height={420} priority /><h1>{item.arabicName}</h1><p>{item.arabicDescription}</p><b>الحصة: {item.servingDescription}</b><div className="nutrition-facts"><Fact label="السعرات الحرارية" value={item.calories} unit="سعر" /><Fact label="البروتين" value={item.proteinGrams} unit="جرام" /><Fact label="الكربوهيدرات" value={item.carbohydratesGrams} unit="جرام" /><Fact label="الدهون" value={item.fatGrams} unit="جرام" /></div><div className={`review-status ${item.dataStatus.toLowerCase()}`}>{item.dataStatus === "DemoUnreviewed" ? "بيانات تجريبية غير مراجعة" : "بيانات مراجعة"}{item.sourceDescription && <small>{item.sourceDescription}</small>}</div></article></>}</GuardianShell>;
}
function Fact({ label, value, unit }: { label: string; value?: number; unit: string }) { return <div><span>{label}</span><b>{value ?? "غير متاح"}</b>{value != null && <small>{unit}</small>}</div>; }

type Medical = { id: string; type: string; arabicTitle: string; recordDate: string; arabicDescription: string; status: string; guardianVisibleNotes?: string };
export function GuardianMedical({ playerId }: { playerId: string }) { const [items, setItems] = useState<Medical[] | null>(null); const [error, setError] = useState(""); useEffect(() => { fetch(`/api/v1/guardian/children/${playerId}/medical`).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(setItems).catch(() => setError("تعذر تحميل السجلات المنشورة.")); }, [playerId]); return <GuardianShell><Link className="back-link" href={`/guardian/children/${playerId}`}>العودة لملف الطفل</Link><header className="guardian-page-header"><span>سجلات منشورة فقط</span><h1>الإصابات والاستشارات الطبية</h1></header>{error && <ErrorState message={error} />}{!items && !error ? <LoadingState /> : items?.length === 0 ? <EmptyState message="لا توجد إصابات أو استشارات منشورة" /> : <div className="medical-list">{items?.map(item => <article key={item.id}><div><span>{typeLabels[item.type]}</span><b>{medicalStatus[item.status]}</b></div><h2>{item.arabicTitle}</h2><small>{item.recordDate}</small><p>{item.arabicDescription}</p>{item.guardianVisibleNotes && <p className="guardian-note">{item.guardianVisibleNotes}</p>}</article>)}</div>}</GuardianShell>; }

type Media = { id: string; type: string; mediaReference: string; thumbnailReference?: string; arabicCaption?: string; capturedAtUtc?: string };
export function GuardianGallery({ playerId }: { playerId: string }) { const [items, setItems] = useState<Media[] | null>(null); const [error, setError] = useState(""); useEffect(() => { fetch(`/api/v1/guardian/children/${playerId}/media`).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(setItems).catch(() => setError("تعذر تحميل المعرض.")); }, [playerId]); return <GuardianShell><Link className="back-link" href={`/guardian/children/${playerId}`}>العودة لملف الطفل</Link><header className="guardian-page-header"><span>وسائط منشورة للطفل</span><h1>الصور والفيديوهات</h1></header>{error && <ErrorState message={error} />}{!items && !error ? <LoadingState /> : items?.length === 0 ? <EmptyState message="لا توجد صور أو فيديوهات منشورة." /> : <div className="gallery-grid">{items?.map(item => <figure key={item.id}><Image src={item.thumbnailReference ?? item.mediaReference} alt={item.arabicCaption ?? "وسائط اللاعب"} width={640} height={420} /><figcaption><span>{typeLabels[item.type]}</span>{item.arabicCaption}</figcaption></figure>)}</div>}</GuardianShell>; }
