import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AdminEnrollmentRequestDetails, AdminEnrollmentRequests, ChildProfile, GuardianHome, GuardianRequestList, NewEnrollmentForm } from "./guardian-core";

const push = vi.fn();
vi.mock("next/navigation", () => ({ useRouter: () => ({ push, replace: vi.fn() }) }));

const home = { academyName: "أكاديمية النجوم الرياضية", guardianName: "سارة محمود", today: "2026-09-28", children: [{ id: "omar", arabicName: "عمر أحمد محمود", dateOfBirth: "2016-04-12", sports: [{ id: "football", sportId: "f", sport: "كرة القدم", group: "مجموعة أ", branch: "مدينة نصر", period: { plan: "شهرية", startDate: "2026-09-01", endDate: "2026-10-01", status: "Expiring" } }, { id: "swim", sportId: "s", sport: "السباحة", group: "مجموعة ب", branch: "التجمع", period: undefined }] }, { id: "mariam", arabicName: "مريم أحمد محمود", dateOfBirth: "2018-07-03", sports: [{ id: "m-football", sportId: "f", sport: "كرة القدم", group: "براعم", branch: "الزقازيق", period: { plan: "شهرية", startDate: "2026-08-01", endDate: "2026-08-31", status: "Expired" } }] }], sportContexts: [{ sportId: "f", sport: "كرة القدم", children: ["عمر أحمد محمود", "مريم أحمد محمود"], childCount: 2 }, { sportId: "s", sport: "السباحة", children: ["عمر أحمد محمود"], childCount: 1 }] };
const ok = (value: unknown) => Promise.resolve(new Response(JSON.stringify(value), { status: 200 }));

beforeEach(() => { push.mockReset(); global.fetch = vi.fn(() => ok(home)); });
afterEach(() => cleanup());

describe("Guardian core experience", () => {
  it("shows the three primary actions", async () => { render(<GuardianHome />); const nav = await screen.findByRole("navigation", { name: "إجراءات الاشتراك" }); expect(within(nav).getByRole("link", { name: /اشتراك جديد/ })).toBeVisible(); expect(within(nav).getByRole("link", { name: /تجديد الاشتراك$/ })).toBeVisible(); expect(within(nav).getByRole("link", { name: /تجديد اشتراك لغيره/ })).toBeVisible(); });
  it("renders one child card with multiple sport badges", async () => { render(<GuardianHome />); const heading = await screen.findByRole("heading", { name: "عمر أحمد محمود" }); const card = heading.closest("article")!; expect(within(card).getAllByText("كرة القدم").length).toBeGreaterThan(0); expect(within(card).getAllByText("السباحة").length).toBeGreaterThan(0); expect(screen.getAllByRole("heading", { name: "عمر أحمد محمود" })).toHaveLength(1); });
  it("deduplicates sport context across children", async () => { render(<GuardianHome />); await screen.findByText("رياضات الأبناء"); const context = screen.getByText("بدون تكرار").closest("section")!; expect(within(context).getAllByRole("heading", { name: "كرة القدم" })).toHaveLength(1); expect(within(context).getAllByRole("heading", { name: "السباحة" })).toHaveLength(1); });
  it("shows expiring expired and no-subscription states with working renewal links", async () => { render(<GuardianHome />); expect(await screen.findByText("الاشتراك ينتهي قريبًا")).toBeVisible(); expect(screen.getByText("الاشتراك منتهي")).toBeVisible(); expect(screen.getByText("لم يتم تفعيل اشتراك بعد")).toBeVisible(); expect(screen.getAllByRole("link", { name: /تجديد الآن|اختيار باقة/ }).length).toBeGreaterThanOrEqual(3); });
  it("offers existing-child and new-child choices without group selection", async () => { global.fetch = vi.fn(() => ok({ children: [{ id: "omar", name: "عمر" }], sports: [{ id: "s", name: "السباحة" }], branches: [{ id: "b", name: "التجمع" }] })); render(<NewEnrollmentForm />); fireEvent.click(screen.getByRole("button", { name: /إضافة رياضة لطفل موجود/ })); expect(await screen.findByLabelText("الطفل")).toBeVisible(); expect(screen.queryByLabelText(/المجموعة/)).not.toBeInTheDocument(); });
  it("shows minimal new child fields", async () => { global.fetch = vi.fn(() => ok({ children: [], sports: [{ id: "s", name: "السباحة" }], branches: [{ id: "b", name: "التجمع" }] })); render(<NewEnrollmentForm />); fireEvent.click(screen.getByRole("button", { name: /إضافة طفل جديد/ })); expect(await screen.findByLabelText("اسم الطفل")).toBeVisible(); expect(screen.getByLabelText("تاريخ الميلاد")).toBeVisible(); expect(screen.getByLabelText(/النوع/)).toBeVisible(); });
  it("tracks request statuses and exposes approved next action", async () => { global.fetch = vi.fn(() => ok([{ id: "r1", child: "عمر", sport: "السباحة", branch: "التجمع", status: "Approved", createdAtUtc: "2026-09-28T00:00:00Z", createdSportEnrollmentId: "e1" }, { id: "r2", child: "مريم", sport: "كرة القدم", branch: "مدينة نصر", status: "Rejected", guardianVisibleReason: "لا توجد مجموعة مناسبة", createdAtUtc: "2026-09-28T00:00:00Z" }])); render(<GuardianRequestList />); expect(await screen.findByText("مقبول")).toBeVisible(); expect(screen.getByText("مرفوض")).toBeVisible(); expect(screen.getByText("لا توجد مجموعة مناسبة")).toBeVisible(); expect(screen.getByRole("link", { name: "إكمال الاشتراك / اختيار الباقة" })).toHaveAttribute("href", "/guardian/renew/e1"); });
  it("integrates report schedule attendance and subscriptions in child profile", async () => { global.fetch = vi.fn(() => ok({ player: { id: "omar", arabicName: "عمر", dateOfBirth: "2016-01-01" }, enrollments: [{ id: "e1", sportId: "f", sport: "كرة القدم", group: "مجموعة أ", branch: "مدينة نصر", recurring: [{ dayOfWeek: "Sunday", startTime: "18:00:00", endTime: "19:30:00" }], upcoming: [], period: { plan: "شهرية", startDate: "2026-09-01", endDate: "2026-10-01", status: "Active" } }], attendance: [{ id: "a1", sessionDate: "2026-09-27", sport: "كرة القدم", group: "مجموعة أ", status: "Present" }], attendanceSummary: { present: 1, absent: 0 }, evaluations: [{ id: "v1", sport: "كرة القدم", evaluationDate: "2026-09-20", reportingPeriod: "شهري" }] })); render(<ChildProfile playerId="omar" />); expect(await screen.findByRole("heading", { name: "تقرير اللاعب" })).toBeVisible(); expect(screen.getByRole("heading", { name: "التدريب والمواعيد" })).toBeVisible(); expect(screen.getByRole("heading", { name: "الحضور" })).toBeVisible(); expect(screen.getByRole("heading", { name: "الاشتراكات" })).toBeVisible(); expect(screen.getByRole("link", { name: "عرض التقرير" })).toHaveAttribute("href", "/guardian/evaluations/v1"); });
  it("renders an empty request state", async () => { global.fetch = vi.fn(() => ok([])); render(<GuardianRequestList />); expect(await screen.findByText("لا توجد طلبات اشتراك حتى الآن.")).toBeVisible(); });
  it("renders a useful loading state", () => { global.fetch = vi.fn(() => new Promise<Response>(() => undefined)); render(<GuardianHome />); expect(screen.getByText("جارٍ تحميل البيانات…")).toBeVisible(); });
  it("renders an Arabic error state", async () => { global.fetch = vi.fn(async () => new Response(null, { status: 500 })); render(<GuardianHome />); await waitFor(() => expect(screen.getByText("تعذر تحميل الصفحة الرئيسية.")).toBeVisible()); });
  it("offers the required admin request filters", async () => { global.fetch = vi.fn((input) => String(input).includes("structure/options") ? ok({ sports: [{ id: "s", arabicName: "السباحة" }], branches: [{ id: "b", arabicName: "التجمع" }] }) : ok([])); render(<AdminEnrollmentRequests />); expect(await screen.findByLabelText("حالة الطلب")).toBeVisible(); expect(screen.getByLabelText("رياضة الطلب")).toBeVisible(); expect(screen.getByLabelText("فرع الطلب")).toBeVisible(); expect(screen.getByLabelText("من تاريخ")).toBeVisible(); expect(screen.getByLabelText("إلى تاريخ")).toBeVisible(); });
  it("shows only explicit safe player matches for a new-child approval", async () => { global.fetch = vi.fn(() => ok({ request: { id: "r1", requestType: "NewChild", child: "ليلى علي", guardian: "سارة", sport: "السباحة", branch: "التجمع", status: "UnderReview" }, groups: [{ id: "g", name: "ناشئات السباحة" }], playerCandidates: [{ id: "p", name: "ليلى علي", playerCode: "PLR-100", dateOfBirth: "2018-02-03" }] })); render(<AdminEnrollmentRequestDetails id="r1" />); expect(await screen.findByLabelText(/مطابقة لاعب موجود/)).toHaveTextContent("PLR-100"); expect(screen.getByLabelText("المجموعة")).toBeVisible(); });
});
