"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ErrorState, LoadingState, PageHeader } from "../components/dashboard-shell";
import { csrfRequest } from "./dashboard-api";
type Child = { id: string; playerCode: string; arabicName: string; relationshipType?: string; isActive: boolean };
type Guardian = { id: string; displayName: string; contactPhone: string; isActive: boolean; children: Child[] };
function useGuardian(id: string) { const [guardian, setGuardian] = useState<Guardian | null>(null); const [error, setError] = useState(""); useEffect(() => { fetch(`/api/v1/people/guardians/${id}`).then(async response => { if (!response.ok) throw new Error(); setGuardian(await response.json() as Guardian); }).catch(() => setError("تعذر تحميل ولي الأمر أو أنه خارج نطاق الأكاديمية.")); }, [id]); return { guardian, error, setError }; }
export function GuardianDetails({ id }: { id: string }) { const { guardian, error } = useGuardian(id); return <><PageHeader title="ملف ولي الأمر" context="أولياء الأمور / عرض" action={{ label: "تعديل البيانات", href: `/dashboard/guardians/${id}/edit` }} />{error ? <ErrorState message={error} /> : !guardian ? <LoadingState /> : <section className="detail-card"><h2>{guardian.displayName}</h2><dl className="detail-grid"><div><dt>رقم الهاتف</dt><dd dir="ltr">{guardian.contactPhone}</dd></div><div><dt>الحالة</dt><dd>{guardian.isActive ? "فعال" : "متوقف"}</dd></div></dl><div className="linked-list"><h3>الأبناء المرتبطون صراحةً</h3>{guardian.children.length ? guardian.children.map(child => <article key={child.id}><div><strong>{child.arabicName}</strong><small>{child.playerCode} · {child.relationshipType ?? "ولي أمر"}</small></div><Link className="small-link" href={`/dashboard/players/${child.id}`}>عرض اللاعب</Link></article>) : <p>لا يوجد أبناء مرتبطون.</p>}</div><Link className="back-link" href="/dashboard/guardians">العودة إلى القائمة</Link></section>}</>; }
export function GuardianEdit({ id }: { id: string }) { const router = useRouter(); const { guardian, error, setError } = useGuardian(id); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await csrfRequest(`/api/v1/people/guardians/${id}`, "PUT", { displayName: data.get("displayName"), contactPhone: data.get("contactPhone") }); router.push(`/dashboard/guardians/${id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر حفظ بيانات ولي الأمر."); } } if (!guardian) return <><PageHeader title="تعديل ولي الأمر" context="أولياء الأمور / تعديل" />{error ? <ErrorState message={error} /> : <LoadingState />}</>; return <><PageHeader title="تعديل بيانات ولي الأمر" context="أولياء الأمور / تعديل" /><form className="form-shell" onSubmit={event => void submit(event)}><label>الاسم<input name="displayName" defaultValue={guardian.displayName} required /></label><label>رقم التواصل داخل الأكاديمية<input name="contactPhone" dir="ltr" defaultValue={guardian.contactPhone} required /><small>لا يغيّر رقم تسجيل الدخول للحساب.</small></label>{error && <ErrorState message={error} />}<div className="form-actions"><button className="primary-button">حفظ التعديلات</button><button type="button" onClick={() => router.back()}>إلغاء</button></div></form></>; }
