import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AttendanceReport, FinancialReport, OwnerDashboard, ReceiptList } from "./reports";
import { ReceiptPrint } from "./receipt-print";

const summary = { asOfDate: "2026-09-28", currency: "EGP", collections: { total: 5000, today: 900, month: 4100 }, payments: { confirmed: 5, failed: 1, pending: 1, cancelled: 0, expired: 0 }, subscriptions: { active: 3, expiring: 1, expired: 1 }, activePlayers: 4, attendance: { sessions: 2, present: 2, absent: 1, notRecorded: 0 }, bySport: [], byBranch: [], latest: [] };
const financial = { from: "2026-09-01", to: "2026-09-28", totalAmount: 900, totalCount: 1, currency: "EGP", items: [{ collectionId: "c1", receiptId: "r1", receiptNumber: "REC-1", player: "عمر", sport: "كرة القدم", branch: "مدينة نصر", group: "مجموعة أ", plan: "شهري", amount: 900, currency: "EGP", paymentMethod: "Online", provider: "Internal", providerReference: "P-1", confirmedAtUtc: "2026-09-28T10:00:00Z" }] };
const attendance = { subject: "players", from: "2026-09-01", to: "2026-09-30", coverage: "StoredRecordsOnly", totalCount: 1, items: [{ id: "a1", date: "2026-09-27", time: "18:00:00", playerCode: "NG-2019", player: "يوسف خالد سمير", birthYear: 2019, sport: "كرة القدم", branch: "مدينة نصر", group: "مجموعة أ", status: "Present", sessionConsumed: false }] };
const options = { sports: [{ id: "s1", arabicName: "كرة القدم" }], branches: [{ id: "b1", arabicName: "مدينة نصر" }], groups: [{ id: "g1", arabicName: "مجموعة أ" }] };

function response(value: unknown, ok = true) { return Promise.resolve(new Response(JSON.stringify(value), { status: ok ? 200 : 403, headers: { "Content-Type": "application/json" } })); }
beforeEach(() => { global.fetch = vi.fn((input) => { const url = String(input); if (url.endsWith("/me")) return response({ role: "AcademyOwner" }); if (url.includes("owner-summary")) return response(summary); if (url.includes("structure/options")) return response(options); if (url.includes("subscriptions/plans")) return response([]); if (url.includes("reports/financial")) return response(financial); if (url.includes("reports/attendance")) return response(attendance); if (url.includes("reports/receipts")) return response({ items: [] }); return response({}); }) as unknown as typeof fetch; });
afterEach(cleanup);

describe("Slice 8A reports", () => {
  it("loads real owner metrics without fake trends", async () => { render(<OwnerDashboard />); expect(await screen.findByText("٥٬٠٠٠ جنيه")).toBeVisible(); expect(screen.getByText("الاشتراكات الفعالة")).toBeVisible(); expect(screen.queryByText(/%/)).not.toBeInTheDocument(); });
  it("shows owner loading state", async () => { let release!: (value: Response) => void; const pending = new Promise<Response>(resolve => { release = resolve; }); global.fetch = vi.fn().mockReturnValueOnce(pending).mockResolvedValueOnce(new Response(JSON.stringify(summary), { status: 200 })) as typeof fetch; render(<OwnerDashboard />); expect(screen.getByRole("status")).toBeVisible(); await act(async () => release(new Response(JSON.stringify({ role: "AcademyOwner" }), { status: 200 }))); expect(await screen.findByText("لوحة المالك")).toBeVisible(); });
  it("shows owner error state", async () => { global.fetch = vi.fn(() => Promise.reject()) as typeof fetch; render(<OwnerDashboard />); expect(await screen.findByRole("alert")).toBeVisible(); });
  it("renders financial confirmed total", async () => { render(<FinancialReport />); expect((await screen.findAllByText("٩٠٠ جنيه"))[0]).toBeVisible(); expect(screen.getByText(/لا تشمل المدفوعات الفاشلة/)).toBeVisible(); });
  it("submits financial filters", async () => { render(<FinancialReport />); await screen.findByText("REC-1 — عمر"); fireEvent.change(screen.getByLabelText("الرياضة"), { target: { value: "s1" } }); fireEvent.click(screen.getByRole("button", { name: "تطبيق الفلاتر" })); await waitFor(() => expect(global.fetch).toHaveBeenCalledWith(expect.stringContaining("sportId=s1"))); });
  it("financial export is an honest CSV link", async () => { render(<FinancialReport />); const link = await screen.findByRole("link", { name: "تصدير CSV" }); expect(link).toHaveAttribute("href", expect.stringContaining("/financial/export")); expect(screen.queryByText(/Excel/)).not.toBeInTheDocument(); });
  it("financial empty state is explicit", async () => { global.fetch = vi.fn((input) => String(input).includes("financial") ? response({ ...financial, totalAmount: 0, totalCount: 0, items: [] }) : String(input).includes("options") ? response(options) : response([])) as unknown as typeof fetch; render(<FinancialReport />); expect(await screen.findByText(/لا توجد تحصيلات مؤكدة/)).toBeVisible(); });
  it("attendance exposes birth-year and operational filters", async () => { render(<AttendanceReport />); expect(await screen.findByText("يوسف خالد سمير", { exact: false })).toBeVisible(); expect(screen.getByLabelText("سنة الميلاد")).toBeVisible(); expect(screen.getByLabelText("المجموعة")).toBeVisible(); });
  it("attendance submits birth year and exports matching query", async () => { render(<AttendanceReport />); await screen.findByText("يوسف خالد سمير", { exact: false }); fireEvent.change(screen.getByLabelText("سنة الميلاد"), { target: { value: "2019" } }); fireEvent.click(screen.getByRole("button", { name: "تطبيق الفلاتر" })); await waitFor(() => expect(global.fetch).toHaveBeenCalledWith(expect.stringContaining("birthYear=2019"))); expect(screen.getByRole("link", { name: "تصدير CSV" })).toHaveAttribute("href", expect.stringContaining("birthYear=2019")); });
  it("receipt list has an empty state", async () => { render(<ReceiptList />); expect(await screen.findByText("لا توجد إيصالات في الفترة الحالية.")).toBeVisible(); });
  it("renders printable Arabic receipt and invokes browser print", async () => { const print = vi.spyOn(window, "print").mockImplementation(() => {}); global.fetch = vi.fn(() => response({ academyName: "أكاديمية النجوم", receiptNumber: "REC-1", playerNameSnapshot: "عمر", sportNameSnapshot: "كرة القدم", planNameSnapshot: "شهري", amount: 900, currency: "EGP", paidAtUtc: "2026-09-28T10:00:00Z", paymentMethod: "الدفع الإلكتروني", providerReference: "P-1" })) as unknown as typeof fetch; render(<ReceiptPrint endpoint="/receipt" />); expect(await screen.findByText("أكاديمية النجوم")).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "طباعة الإيصال" })); expect(print).toHaveBeenCalledOnce(); print.mockRestore(); });
  it("renders discounted receipt original discount and final paid amount", async () => { global.fetch = vi.fn(() => response({ academyName: "أكاديمية النجوم", receiptNumber: "REC-D", playerNameSnapshot: "عمر", sportNameSnapshot: "كرة القدم", planNameSnapshot: "شهري", originalAmount: 900, discountType: "Percentage", discountValue: 10, discountAmount: 90, finalAmount: 810, amount: 810, currency: "EGP", paidAtUtc: "2026-09-28T10:00:00Z", paymentMethod: "الدفع الإلكتروني", providerReference: "P-D" })) as unknown as typeof fetch; render(<ReceiptPrint endpoint="/receipt" />); expect(await screen.findByText("السعر الأصلي")).toBeVisible(); expect(screen.getByText("الخصم").parentElement).toHaveTextContent(/10%.*٩٠/); expect(screen.getByText("المبلغ المدفوع").parentElement).toHaveTextContent(/٨١٠/); });
  it("shows receipt authorization/loading failure", async () => { global.fetch = vi.fn(() => response({}, false)) as unknown as typeof fetch; render(<ReceiptPrint endpoint="/receipt" />); expect(await screen.findByRole("alert")).toHaveTextContent("لا تملك صلاحية"); });
});
