"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ConfirmationDialog, ErrorState, LoadingState, PageHeader, RowActions } from "../components/dashboard-shell";
import { csrfRequest } from "./dashboard-api";

export type StructureKind = "branches" | "sports" | "categories" | "groups" | "coaches";
type RecordData = { id: string; arabicName: string; englishName?: string; description?: string; isActive: boolean; minimumBirthYear?: number; maximumBirthYear?: number; branchId?: string; sportId?: string; ageCategoryId?: string; capacity?: number; branchName?: string; sportName?: string; categoryName?: string; assignments?: Assignment[] };
type Assignment = { id: string; groupName: string; isActive: boolean };
type Option = { id: string; arabicName: string };
type Options = { branches: Option[]; sports: Option[]; categories: Option[] };
const titles: Record<StructureKind, string> = { branches: "الفرع", sports: "الرياضة", categories: "الفئة العمرية", groups: "المجموعة", coaches: "المدرب" };

export function StructureDetails({ kind, id }: { kind: StructureKind; id: string }) {
  const [record, setRecord] = useState<RecordData | null>(null);
  const [error, setError] = useState("");
  const [target, setTarget] = useState<Assignment | null>(null);
  useEffect(() => { fetch(`/api/v1/manage/structure/${kind}/${id}`).then(async response => { if (!response.ok) throw new Error(); setRecord(await response.json() as RecordData); }).catch(() => setError("تعذر تحميل السجل أو أنه خارج نطاق الأكاديمية.")); }, [id, kind]);
  async function changeAssignment() { if (!target) return; try { await csrfRequest(`/api/v1/manage/group-assignments/${target.id}/status`, "PUT", { isActive: !target.isActive }); const response = await fetch(`/api/v1/manage/structure/${kind}/${id}`); if (!response.ok) throw new Error("تعذر تحديث البيانات."); setRecord(await response.json() as RecordData); setTarget(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر تحديث الإسناد."); } }
  return <><PageHeader title={`عرض ${titles[kind]}`} context={`الأكاديمية / ${titles[kind]}`} action={kind === "coaches" ? { label: "إسناد مجموعة", href: "/dashboard/academy/coaches/new" } : { label: "تعديل", href: `/dashboard/academy/${kind}/${id}/edit` }} />{error ? <ErrorState message={error} /> : !record ? <LoadingState /> : <section className="detail-card"><h2>{record.arabicName}</h2><dl className="detail-grid"><div><dt>الحالة</dt><dd>{record.isActive ? "فعال" : "متوقف"}</dd></div>{record.englishName && <div><dt>الاسم بالإنجليزية</dt><dd dir="ltr">{record.englishName}</dd></div>}{record.description && <div><dt>الوصف/العنوان</dt><dd>{record.description}</dd></div>}{record.branchName && <div><dt>الفرع</dt><dd>{record.branchName}</dd></div>}{record.sportName && <div><dt>الرياضة</dt><dd>{record.sportName}</dd></div>}{record.categoryName && <div><dt>الفئة العمرية</dt><dd>{record.categoryName}</dd></div>}</dl>{kind === "coaches" && <div className="linked-list"><h3>المجموعات المسندة</h3>{record.assignments?.length ? record.assignments.map(assignment => <article key={assignment.id} className={!assignment.isActive ? "inactive-record" : ""}><strong>{assignment.groupName}</strong><RowActions actions={[{ label: assignment.isActive ? "إزالة الإسناد" : "إعادة الإسناد", onClick: () => setTarget(assignment), tone: assignment.isActive ? "danger" : "normal" }]} /></article>) : <p>لا توجد مجموعات مسندة.</p>}</div>}<Link className="back-link" href={`/dashboard/academy/${kind}`}>العودة إلى القائمة</Link></section>}<ConfirmationDialog open={target !== null} title="تأكيد تحديث الإسناد" message={`هل تريد ${target?.isActive ? "إزالة" : "إعادة"} إسناد «${target?.groupName ?? ""}»؟`} confirmLabel="تأكيد" onConfirm={() => void changeAssignment()} onCancel={() => setTarget(null)} /></>;
}

export function StructureEdit({ kind, id }: { kind: Exclude<StructureKind, "coaches">; id: string }) {
  const router = useRouter();
  const [record, setRecord] = useState<RecordData | null>(null);
  const [options, setOptions] = useState<Options>({ branches: [], sports: [], categories: [] });
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch(`/api/v1/manage/structure/${kind}/${id}`), fetch("/api/v1/manage/structure/options")]).then(async ([recordResponse, optionsResponse]) => { if (!recordResponse.ok || !optionsResponse.ok) throw new Error(); setRecord(await recordResponse.json() as RecordData); setOptions(await optionsResponse.json() as Options); }).catch(() => setError("تعذر تحميل بيانات التعديل.")); }, [id, kind]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await csrfRequest(`/api/v1/manage/structure/${kind}/${id}`, "PUT", { arabicName: data.get("arabicName"), englishName: data.get("englishName"), description: data.get("description"), minimumBirthYear: Number(data.get("minimumBirthYear")) || null, maximumBirthYear: Number(data.get("maximumBirthYear")) || null, branchId: data.get("branchId") || null, sportId: data.get("sportId") || null, ageCategoryId: data.get("ageCategoryId") || null, capacity: Number(data.get("capacity")) || null }); router.push(`/dashboard/academy/${kind}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر حفظ التعديل."); } }
  if (!record) return <><PageHeader title={`تعديل ${titles[kind]}`} context="الأكاديمية / تعديل" />{error ? <ErrorState message={error} /> : <LoadingState />}</>;
  return <><PageHeader title={`تعديل ${titles[kind]}`} context={`الأكاديمية / ${titles[kind]} / تعديل`} /><form className="form-shell" onSubmit={event => void submit(event)}><label>الاسم بالعربية<input name="arabicName" defaultValue={record.arabicName} required /></label><label>الاسم بالإنجليزية<input name="englishName" dir="ltr" defaultValue={record.englishName ?? ""} /></label>{kind === "branches" && <label>العنوان المختصر<input name="description" defaultValue={record.description ?? ""} /></label>}{kind === "categories" && <><label>أقل سنة ميلاد<input name="minimumBirthYear" type="number" defaultValue={record.minimumBirthYear ?? ""} /></label><label>أعلى سنة ميلاد<input name="maximumBirthYear" type="number" defaultValue={record.maximumBirthYear ?? ""} /></label></>}{kind === "groups" && <><label>الفرع<select name="branchId" defaultValue={record.branchId} required>{options.branches.map(option => <option key={option.id} value={option.id}>{option.arabicName}</option>)}</select></label><label>الرياضة<select name="sportId" defaultValue={record.sportId} required>{options.sports.map(option => <option key={option.id} value={option.id}>{option.arabicName}</option>)}</select></label><label>الفئة العمرية<select name="ageCategoryId" defaultValue={record.ageCategoryId} required>{options.categories.map(option => <option key={option.id} value={option.id}>{option.arabicName}</option>)}</select></label><label>السعة<input name="capacity" type="number" min="1" defaultValue={record.capacity ?? ""} /></label></>}{error && <ErrorState message={error} />}<div className="form-actions"><button className="primary-button">حفظ التعديلات</button><button type="button" onClick={() => router.back()}>إلغاء</button></div></form></>;
}
