"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { EmptyState, ErrorState, ListSearch, LoadingState, PageHeader, RowActions } from "../components/dashboard-shell";
import { csrfRequest } from "./dashboard-api";

type Row = Record<string, string | number | null> & { id: string };
const listConfig: Record<string, { title: string; endpoint: string }> = {
  current: { title: "الاشتراكات الحالية", endpoint: "/api/v1/subscriptions/periods?state=active" },
  expiring: { title: "الاشتراكات التي تنتهي قريباً", endpoint: "/api/v1/subscriptions/periods?state=expiring" },
  expired: { title: "الاشتراكات المنتهية", endpoint: "/api/v1/subscriptions/periods?state=expired" },
  renewals: { title: "طلبات التجديد", endpoint: "/api/v1/subscriptions/renewals" },
  payments: { title: "طلبات الدفع", endpoint: "/api/v1/subscriptions/payments" },
};
export function SubscriptionOperationalList({ kind }: { kind: keyof typeof listConfig }) {
  const config = listConfig[kind]; const [rows, setRows] = useState<Row[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetch(config.endpoint).then(async r => { if (!r.ok) throw new Error(); setRows(await r.json() as Row[]); }).catch(() => setError("تعذر تحميل البيانات.")).finally(() => setLoading(false)); }, [config.endpoint]);
  const filtered = useMemo(() => rows.filter(row => JSON.stringify(row).toLocaleLowerCase("ar").includes(search.toLocaleLowerCase("ar"))), [rows, search]);
  return <><PageHeader title={config.title} context={`الاشتراكات / ${config.title}`} /><section className="list-card"><ListSearch value={search} onChange={setSearch} />{error && <ErrorState message={error} />}{loading ? <LoadingState /> : !filtered.length ? <EmptyState /> : <div className="data-list">{filtered.map(row => <article key={row.id}><div><strong>{String(row.player ?? row.reference ?? "سجل")}</strong><small>{[row.sport, row.plan, row.amount && `${row.amount} ${row.currency}`, row.status, row.startDate, row.endDate].filter(Boolean).join(" · ")}</small></div></article>)}</div>}</section></>;
}
export function CollectionList() { const [data, setData] = useState<{ total: number; items: Row[] } | null>(null); useEffect(() => { fetch("/api/v1/subscriptions/collections").then(r => r.json()).then(setData); }, []); return <><PageHeader title="التحصيلات" context="الاشتراكات / التحصيلات" />{!data ? <LoadingState /> : <section className="list-card"><p className="metric">إجمالي التحصيل المؤكد: {data.total} EGP</p><div className="data-list">{data.items.map(row => <article key={row.id}><div><strong>{String(row.receiptNumber)} — {String(row.player)}</strong><small>{row.sport} · {row.amount} {row.currency} · {row.provider}</small></div><RowActions actions={[{ label: "عرض الإيصال", href: `/dashboard/subscriptions/receipts/${row.receiptId}` }]} /></article>)}</div></section>}</> }

type Plan = { id: string; arabicName: string; sport: string; sportId: string; planType: string; price: number; currency: string; durationDays?: number; sessionCount?: number; isActive: boolean };
export function PlanList() { const [plans, setPlans] = useState<Plan[]>([]); const [search, setSearch] = useState(""); const load = () => fetch("/api/v1/subscriptions/plans").then(r => r.json()).then(setPlans); useEffect(() => { void load(); }, []); async function status(plan: Plan) { await csrfRequest(`/api/v1/subscriptions/plans/${plan.id}/status`, "PUT", { isActive: !plan.isActive }); await load(); } return <><PageHeader title="الباقات" context="الاشتراكات / الباقات" action={{ label: "إضافة باقة", href: "/dashboard/subscriptions/plans/new" }} /><section className="list-card"><ListSearch value={search} onChange={setSearch} /> <div className="data-list">{plans.filter(x => x.arabicName.includes(search)).map(plan => <article key={plan.id}><div><strong>{plan.arabicName}</strong><small>{plan.sport} · {plan.planType} · {plan.price} {plan.currency} · {plan.durationDays ? `${plan.durationDays} يوم` : ""} {plan.sessionCount ? `${plan.sessionCount} حصة` : ""} · {plan.isActive ? "فعال" : "متوقف"}</small></div><RowActions actions={[{ label: "عرض", href: `/dashboard/subscriptions/plans/${plan.id}` }, { label: "تعديل", href: `/dashboard/subscriptions/plans/${plan.id}/edit` }, { label: plan.isActive ? "إيقاف" : "تفعيل", onClick: () => void status(plan) }]} /></article>)}</div></section></>; }

export function PlanForm({ id, readOnly = false }: { id?: string; readOnly?: boolean }) { const router = useRouter(); const [sports, setSports] = useState<{ id: string; arabicName: string }[]>([]); const [plan, setPlan] = useState<Partial<Plan>>({ planType: "Duration", currency: "EGP" }); const [error, setError] = useState(""); useEffect(() => { fetch("/api/v1/manage/structure/options").then(r => r.json()).then(x => setSports(x.sports)); if (id) fetch(`/api/v1/subscriptions/plans/${id}`).then(r => r.json()).then(setPlan); }, [id]); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const type = String(f.get("planType")); const body = { arabicName: f.get("arabicName"), englishName: f.get("englishName") || null, sportId: f.get("sportId"), planType: type === "Duration" ? 1 : type === "Sessions" ? 2 : 3, price: Number(f.get("price")), durationDays: f.get("durationDays") ? Number(f.get("durationDays")) : null, sessionCount: f.get("sessionCount") ? Number(f.get("sessionCount")) : null, displayOrder: Number(f.get("displayOrder") ?? 0) }; try { await csrfRequest(id ? `/api/v1/subscriptions/plans/${id}` : "/api/v1/subscriptions/plans", id ? "PUT" : "POST", body); router.push("/dashboard/subscriptions/plans"); } catch (e) { setError(e instanceof Error ? e.message : "تعذر الحفظ"); } } return <><PageHeader title={readOnly ? "عرض الباقة" : id ? "تعديل الباقة" : "إضافة باقة"} context="الاشتراكات / الباقات" />{readOnly ? <section className="detail-card"><h2>{plan.arabicName}</h2><p>{plan.sport} · {plan.planType} · {plan.price} EGP</p><Link href={`/dashboard/subscriptions/plans/${id}/edit`}>تعديل</Link></section> : <form className="form-shell" onSubmit={e => void submit(e)}><label>الاسم العربي<input name="arabicName" required defaultValue={plan.arabicName} /></label><label>الاسم الإنجليزي<input name="englishName" defaultValue="" /></label><label>الرياضة<select name="sportId" required value={plan.sportId ?? ""} onChange={e => setPlan({ ...plan, sportId: e.target.value })}><option value="">اختر</option>{sports.map(x => <option key={x.id} value={x.id}>{x.arabicName}</option>)}</select></label><label>النوع<select name="planType" value={plan.planType} onChange={e => setPlan({ ...plan, planType: e.target.value })}><option>Duration</option><option>Sessions</option><option>Combined</option></select></label><label>السعر<input name="price" type="number" min="0.01" step="0.01" required defaultValue={plan.price} /></label><label>عدد الأيام<input name="durationDays" type="number" min="1" defaultValue={plan.durationDays} /></label><label>عدد الحصص<input name="sessionCount" type="number" min="1" defaultValue={plan.sessionCount} /></label><input name="displayOrder" type="hidden" value="0" />{error && <ErrorState message={error} />}<button className="primary-button">حفظ</button></form>}</>; }
